// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/auth_provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthProvider_Authenticate_FullMethodName   = "/silo.plugin.v1.AuthProvider/Authenticate"
	AuthProvider_InitAuthorize_FullMethodName  = "/silo.plugin.v1.AuthProvider/InitAuthorize"
	AuthProvider_ExchangeCode_FullMethodName   = "/silo.plugin.v1.AuthProvider/ExchangeCode"
	AuthProvider_RefreshSession_FullMethodName = "/silo.plugin.v1.AuthProvider/RefreshSession"
)

// AuthProviderClient is the client API for AuthProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthProviderClient interface {
	// Authenticate handles password-based login. Existing surface.
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// InitAuthorize starts an OAuth/OIDC authorization-code flow. The plugin
	// returns the URL to redirect the user agent to, plus opaque provider_state
	// (e.g., PKCE verifier) the host stores and round-trips on the callback.
	InitAuthorize(ctx context.Context, in *InitAuthorizeRequest, opts ...grpc.CallOption) (*InitAuthorizeResponse, error)
	// ExchangeCode exchanges the authorization code for tokens, decodes the
	// user identity, and returns the same shape as Authenticate.
	ExchangeCode(ctx context.Context, in *ExchangeCodeRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// RefreshSession optionally refreshes a previously-issued session using
	// provider-specific refresh state. Plugins that don't support refresh
	// should return Unimplemented.
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthProviderClient(cc grpc.ClientConnInterface) AuthProviderClient {
	return &authProviderClient{cc}
}

func (c *authProviderClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AuthProvider_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authProviderClient) InitAuthorize(ctx context.Context, in *InitAuthorizeRequest, opts ...grpc.CallOption) (*InitAuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitAuthorizeResponse)
	err := c.cc.Invoke(ctx, AuthProvider_InitAuthorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authProviderClient) ExchangeCode(ctx context.Context, in *ExchangeCodeRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AuthProvider_ExchangeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authProviderClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AuthProvider_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthProviderServer is the server API for AuthProvider service.
// All implementations should embed UnimplementedAuthProviderServer
// for forward compatibility.
type AuthProviderServer interface {
	// Authenticate handles password-based login. Existing surface.
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// InitAuthorize starts an OAuth/OIDC authorization-code flow. The plugin
	// returns the URL to redirect the user agent to, plus opaque provider_state
	// (e.g., PKCE verifier) the host stores and round-trips on the callback.
	InitAuthorize(context.Context, *InitAuthorizeRequest) (*InitAuthorizeResponse, error)
	// ExchangeCode exchanges the authorization code for tokens, decodes the
	// user identity, and returns the same shape as Authenticate.
	ExchangeCode(context.Context, *ExchangeCodeRequest) (*AuthenticateResponse, error)
	// RefreshSession optionally refreshes a previously-issued session using
	// provider-specific refresh state. Plugins that don't support refresh
	// should return Unimplemented.
	RefreshSession(context.Context, *RefreshSessionRequest) (*AuthenticateResponse, error)
}

// UnimplementedAuthProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthProviderServer struct{}

func (UnimplementedAuthProviderServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAuthProviderServer) InitAuthorize(context.Context, *InitAuthorizeRequest) (*InitAuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitAuthorize not implemented")
}
func (UnimplementedAuthProviderServer) ExchangeCode(context.Context, *ExchangeCodeRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeCode not implemented")
}
func (UnimplementedAuthProviderServer) RefreshSession(context.Context, *RefreshSessionRequest) (*AuthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedAuthProviderServer) testEmbeddedByValue() {}

// UnsafeAuthProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthProviderServer will
// result in compilation errors.
type UnsafeAuthProviderServer interface {
	mustEmbedUnimplementedAuthProviderServer()
}

func RegisterAuthProviderServer(s grpc.ServiceRegistrar, srv AuthProviderServer) {
	// If the following call panics, it indicates UnimplementedAuthProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthProvider_ServiceDesc, srv)
}

func _AuthProvider_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProvider_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthProvider_InitAuthorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitAuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderServer).InitAuthorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProvider_InitAuthorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderServer).InitAuthorize(ctx, req.(*InitAuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthProvider_ExchangeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderServer).ExchangeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProvider_ExchangeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderServer).ExchangeCode(ctx, req.(*ExchangeCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthProvider_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProvider_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthProvider_ServiceDesc is the grpc.ServiceDesc for AuthProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.AuthProvider",
	HandlerType: (*AuthProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthProvider_Authenticate_Handler,
		},
		{
			MethodName: "InitAuthorize",
			Handler:    _AuthProvider_InitAuthorize_Handler,
		},
		{
			MethodName: "ExchangeCode",
			Handler:    _AuthProvider_ExchangeCode_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _AuthProvider_RefreshSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/auth_provider.proto",
}

const (
	AuthProviderChecks_TestConnection_FullMethodName = "/silo.plugin.v1.AuthProviderChecks/TestConnection"
	AuthProviderChecks_CheckAccount_FullMethodName   = "/silo.plugin.v1.AuthProviderChecks/CheckAccount"
	AuthProviderChecks_EndSessionUrl_FullMethodName  = "/silo.plugin.v1.AuthProviderChecks/EndSessionUrl"
)

// AuthProviderChecksClient is the client API for AuthProviderChecks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthProviderChecks is separate from AuthProvider so adding these RPCs does
// not add methods to the released AuthProviderServer Go interface. Register it
// with runtime.WithAuthProviderChecks; the SDK runtime also registers it when
// the AuthProvider server itself implements AuthProviderChecksServer.
//
// Plugins that do not serve it answer Unimplemented. Hosts treat an
// Unimplemented TestConnection as "no connection test", an Unimplemented
// CheckAccount like CHECK_ACCOUNT_STATUS_UNSUPPORTED (the account's sessions
// get an absolute age limit and do not slide), and an Unimplemented
// EndSessionUrl like an empty url.
type AuthProviderChecksClient interface {
	// TestConnection checks staged, unsaved configuration. The plugin tests the
	// config in the request, never its running configuration, and persists
	// nothing. Advertise support with the capability metadata key
	// "connection_test": true.
	TestConnection(ctx context.Context, in *AuthTestConnectionRequest, opts ...grpc.CallOption) (*AuthTestConnectionResponse, error)
	// CheckAccount re-checks a previously authenticated account against the
	// provider without user interaction, for example with a stored refresh
	// token or a directory lookup. It replaces RefreshSession, which the host
	// does not call.
	//
	// Host guarantees: at most one CheckAccount is in flight per (installation,
	// external_subject) across all nodes, and the host persists a rotated
	// account.refresh_state (for example under a row lock or compare-and-swap)
	// before it makes the next call for that account. A plugin can therefore
	// rotate a single-use refresh token without two nodes presenting the same
	// token.
	CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error)
	// EndSessionUrl returns the provider logout URL the host sends the browser
	// to on web sign-out, such as an OIDC end_session_endpoint with
	// id_token_hint. The host ends the Silo session whatever the answer.
	EndSessionUrl(ctx context.Context, in *AuthEndSessionUrlRequest, opts ...grpc.CallOption) (*AuthEndSessionUrlResponse, error)
}

type authProviderChecksClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthProviderChecksClient(cc grpc.ClientConnInterface) AuthProviderChecksClient {
	return &authProviderChecksClient{cc}
}

func (c *authProviderChecksClient) TestConnection(ctx context.Context, in *AuthTestConnectionRequest, opts ...grpc.CallOption) (*AuthTestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthTestConnectionResponse)
	err := c.cc.Invoke(ctx, AuthProviderChecks_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authProviderChecksClient) CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccountResponse)
	err := c.cc.Invoke(ctx, AuthProviderChecks_CheckAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authProviderChecksClient) EndSessionUrl(ctx context.Context, in *AuthEndSessionUrlRequest, opts ...grpc.CallOption) (*AuthEndSessionUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthEndSessionUrlResponse)
	err := c.cc.Invoke(ctx, AuthProviderChecks_EndSessionUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthProviderChecksServer is the server API for AuthProviderChecks service.
// All implementations should embed UnimplementedAuthProviderChecksServer
// for forward compatibility.
//
// AuthProviderChecks is separate from AuthProvider so adding these RPCs does
// not add methods to the released AuthProviderServer Go interface. Register it
// with runtime.WithAuthProviderChecks; the SDK runtime also registers it when
// the AuthProvider server itself implements AuthProviderChecksServer.
//
// Plugins that do not serve it answer Unimplemented. Hosts treat an
// Unimplemented TestConnection as "no connection test", an Unimplemented
// CheckAccount like CHECK_ACCOUNT_STATUS_UNSUPPORTED (the account's sessions
// get an absolute age limit and do not slide), and an Unimplemented
// EndSessionUrl like an empty url.
type AuthProviderChecksServer interface {
	// TestConnection checks staged, unsaved configuration. The plugin tests the
	// config in the request, never its running configuration, and persists
	// nothing. Advertise support with the capability metadata key
	// "connection_test": true.
	TestConnection(context.Context, *AuthTestConnectionRequest) (*AuthTestConnectionResponse, error)
	// CheckAccount re-checks a previously authenticated account against the
	// provider without user interaction, for example with a stored refresh
	// token or a directory lookup. It replaces RefreshSession, which the host
	// does not call.
	//
	// Host guarantees: at most one CheckAccount is in flight per (installation,
	// external_subject) across all nodes, and the host persists a rotated
	// account.refresh_state (for example under a row lock or compare-and-swap)
	// before it makes the next call for that account. A plugin can therefore
	// rotate a single-use refresh token without two nodes presenting the same
	// token.
	CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountResponse, error)
	// EndSessionUrl returns the provider logout URL the host sends the browser
	// to on web sign-out, such as an OIDC end_session_endpoint with
	// id_token_hint. The host ends the Silo session whatever the answer.
	EndSessionUrl(context.Context, *AuthEndSessionUrlRequest) (*AuthEndSessionUrlResponse, error)
}

// UnimplementedAuthProviderChecksServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthProviderChecksServer struct{}

func (UnimplementedAuthProviderChecksServer) TestConnection(context.Context, *AuthTestConnectionRequest) (*AuthTestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedAuthProviderChecksServer) CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccount not implemented")
}
func (UnimplementedAuthProviderChecksServer) EndSessionUrl(context.Context, *AuthEndSessionUrlRequest) (*AuthEndSessionUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSessionUrl not implemented")
}
func (UnimplementedAuthProviderChecksServer) testEmbeddedByValue() {}

// UnsafeAuthProviderChecksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthProviderChecksServer will
// result in compilation errors.
type UnsafeAuthProviderChecksServer interface {
	mustEmbedUnimplementedAuthProviderChecksServer()
}

func RegisterAuthProviderChecksServer(s grpc.ServiceRegistrar, srv AuthProviderChecksServer) {
	// If the following call panics, it indicates UnimplementedAuthProviderChecksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthProviderChecks_ServiceDesc, srv)
}

func _AuthProviderChecks_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderChecksServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProviderChecks_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderChecksServer).TestConnection(ctx, req.(*AuthTestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthProviderChecks_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderChecksServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProviderChecks_CheckAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderChecksServer).CheckAccount(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthProviderChecks_EndSessionUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthEndSessionUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthProviderChecksServer).EndSessionUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthProviderChecks_EndSessionUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthProviderChecksServer).EndSessionUrl(ctx, req.(*AuthEndSessionUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthProviderChecks_ServiceDesc is the grpc.ServiceDesc for AuthProviderChecks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthProviderChecks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.AuthProviderChecks",
	HandlerType: (*AuthProviderChecksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _AuthProviderChecks_TestConnection_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _AuthProviderChecks_CheckAccount_Handler,
		},
		{
			MethodName: "EndSessionUrl",
			Handler:    _AuthProviderChecks_EndSessionUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/auth_provider.proto",
}
