// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/request_router.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDescriptor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MediaType          string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // "movie" | "series"
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year               int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	ExternalIds        map[string]string      `protobuf:"bytes,4,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsAnime            bool                   `protobuf:"varint,5,opt,name=is_anime,json=isAnime,proto3" json:"is_anime,omitempty"`
	RequesterUserId    int64                  `protobuf:"varint,6,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	RequesterProfileId string                 `protobuf:"bytes,7,opt,name=requester_profile_id,json=requesterProfileId,proto3" json:"requester_profile_id,omitempty"`
	// requester identity for plugins that attribute requests to a per-user account
	// on the downstream service (e.g. Seerr). Empty when the host cannot resolve it.
	RequesterEmail    string `protobuf:"bytes,8,opt,name=requester_email,json=requesterEmail,proto3" json:"requester_email,omitempty"`
	RequesterUsername string `protobuf:"bytes,9,opt,name=requester_username,json=requesterUsername,proto3" json:"requester_username,omitempty"`
	// seasons lists the requested season numbers of a series; 0 is Specials.
	// Empty means the whole series, which is what every request meant before
	// this field existed. Only set when media_type is "series". Plugins that
	// declare RequestRouterDescriptor.supports_seasons must fulfil only these
	// seasons; see that field for the full contract.
	Seasons       []int32 `protobuf:"varint,10,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDescriptor) Reset() {
	*x = RequestDescriptor{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDescriptor) ProtoMessage() {}

func (x *RequestDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDescriptor.ProtoReflect.Descriptor instead.
func (*RequestDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDescriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *RequestDescriptor) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestDescriptor) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestDescriptor) GetExternalIds() map[string]string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *RequestDescriptor) GetIsAnime() bool {
	if x != nil {
		return x.IsAnime
	}
	return false
}

func (x *RequestDescriptor) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *RequestDescriptor) GetRequesterProfileId() string {
	if x != nil {
		return x.RequesterProfileId
	}
	return ""
}

func (x *RequestDescriptor) GetRequesterEmail() string {
	if x != nil {
		return x.RequesterEmail
	}
	return ""
}

func (x *RequestDescriptor) GetRequesterUsername() string {
	if x != nil {
		return x.RequesterUsername
	}
	return ""
}

func (x *RequestDescriptor) GetSeasons() []int32 {
	if x != nil {
		return x.Seasons
	}
	return nil
}

// RequestRouterDescriptor is typed request_router.v1 contract metadata that the
// host reads from the manifest without launching the plugin. An absent
// descriptor means every flag is false, which is how the host treats plugins
// built before a flag existed.
type RequestRouterDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// supports_seasons declares that Fulfill and CheckStatus honour
	// RequestDescriptor.seasons. A declaring plugin acquires only the listed
	// seasons; when the series already exists upstream it adds those seasons to
	// what is already tracked and leaves other seasons unchanged. Repeating a
	// request converges rather than duplicating work. The host sends a request
	// for only the missing seasons of a series it already has only to plugins
	// that set this flag, because other plugins would add the whole series.
	SupportsSeasons bool `protobuf:"varint,1,opt,name=supports_seasons,json=supportsSeasons,proto3" json:"supports_seasons,omitempty"`
	// reports_download_progress declares that CheckStatus fills
	// TargetStatus.progress for targets with downloads in flight. The host
	// notices progress on its regular reconcile pass, then asks a declaring
	// plugin every minute about a target that is downloading and has reported
	// progress. A target whose progress comes back unset drops back to the
	// regular cadence. Hosts ignore progress from plugins that do not declare
	// this.
	ReportsDownloadProgress bool `protobuf:"varint,2,opt,name=reports_download_progress,json=reportsDownloadProgress,proto3" json:"reports_download_progress,omitempty"`
	// wording is how clients describe a request while this plugin fulfils it.
	// Unset, or any field left empty, means the host's own neutral words.
	Wording       *RequestRouterWording `protobuf:"bytes,3,opt,name=wording,proto3" json:"wording,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRouterDescriptor) Reset() {
	*x = RequestRouterDescriptor{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRouterDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRouterDescriptor) ProtoMessage() {}

func (x *RequestRouterDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRouterDescriptor.ProtoReflect.Descriptor instead.
func (*RequestRouterDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{1}
}

func (x *RequestRouterDescriptor) GetSupportsSeasons() bool {
	if x != nil {
		return x.SupportsSeasons
	}
	return false
}

func (x *RequestRouterDescriptor) GetReportsDownloadProgress() bool {
	if x != nil {
		return x.ReportsDownloadProgress
	}
	return false
}

func (x *RequestRouterDescriptor) GetWording() *RequestRouterWording {
	if x != nil {
		return x.Wording
	}
	return nil
}

// RequestRouterWording names the part of a request that a request router
// handles, in words that fit how the plugin works. Clients draw a request as
// four steps: requested, approved, the router's step, and in the library. The
// router names only its own step and the two statuses it reports while the
// request is on it; the host words the other steps. Clients show these words
// to everyone who can see the request, so keep them plain English and leave
// out release names, indexers, download clients and paths. Every value is a
// single line without leading or trailing spaces.
type RequestRouterWording struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// step names the router's step on the request's track, e.g. "Processing".
	// At most 24 characters.
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// queued describes a request whose live targets are all queued: accepted
	// by the downstream service, with nothing moving yet.
	Queued *RequestStatusWording `protobuf:"bytes,2,opt,name=queued,proto3" json:"queued,omitempty"`
	// downloading describes a request with at least one downloading target.
	Downloading   *RequestStatusWording `protobuf:"bytes,3,opt,name=downloading,proto3" json:"downloading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRouterWording) Reset() {
	*x = RequestRouterWording{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRouterWording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRouterWording) ProtoMessage() {}

func (x *RequestRouterWording) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRouterWording.ProtoReflect.Descriptor instead.
func (*RequestRouterWording) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{2}
}

func (x *RequestRouterWording) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *RequestRouterWording) GetQueued() *RequestStatusWording {
	if x != nil {
		return x.Queued
	}
	return nil
}

func (x *RequestRouterWording) GetDownloading() *RequestStatusWording {
	if x != nil {
		return x.Downloading
	}
	return nil
}

// RequestStatusWording describes one status of a request on the router's step.
type RequestStatusWording struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// label is one to three words for cards, list rows and the current step,
	// e.g. "Searching". At most 24 characters.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// detail is one sentence shown under the current step on the request's
	// page, e.g. "Seerr takes it from here." At most 140 characters.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStatusWording) Reset() {
	*x = RequestStatusWording{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStatusWording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStatusWording) ProtoMessage() {}

func (x *RequestStatusWording) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStatusWording.ProtoReflect.Descriptor instead.
func (*RequestStatusWording) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{3}
}

func (x *RequestStatusWording) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RequestStatusWording) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type RouterConnection struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseUrl string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey  string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// plugin-declared config blob (e.g. service_kind, root_folder,
	// quality_profile_id)
	Config        *structpb.Struct `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterConnection) Reset() {
	*x = RouterConnection{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterConnection) ProtoMessage() {}

func (x *RouterConnection) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterConnection.ProtoReflect.Descriptor instead.
func (*RouterConnection) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{4}
}

func (x *RouterConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouterConnection) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *RouterConnection) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RouterConnection) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// RequestedQuality is one quality tier the host wants fulfilled. The host owns
// quality governance, so it stamps is4k rather than each plugin re-deriving it
// from the id string. id is the tier identity echoed back as
// FulfillmentTarget.quality (e.g. "1080p" / "2160p").
type RequestedQuality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Is4K          bool                   `protobuf:"varint,2,opt,name=is4k,proto3" json:"is4k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedQuality) Reset() {
	*x = RequestedQuality{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedQuality) ProtoMessage() {}

func (x *RequestedQuality) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedQuality.ProtoReflect.Descriptor instead.
func (*RequestedQuality) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{5}
}

func (x *RequestedQuality) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestedQuality) GetIs4K() bool {
	if x != nil {
		return x.Is4K
	}
	return false
}

type FulfillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Request       *RequestDescriptor     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Qualities     []*RequestedQuality    `protobuf:"bytes,3,rep,name=qualities,proto3" json:"qualities,omitempty"`
	Connections   []*RouterConnection    `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillRequest) Reset() {
	*x = FulfillRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillRequest) ProtoMessage() {}

func (x *FulfillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillRequest.ProtoReflect.Descriptor instead.
func (*FulfillRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{6}
}

func (x *FulfillRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *FulfillRequest) GetRequest() *RequestDescriptor {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FulfillRequest) GetQualities() []*RequestedQuality {
	if x != nil {
		return x.Qualities
	}
	return nil
}

func (x *FulfillRequest) GetConnections() []*RouterConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type FulfillmentTarget struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Quality      string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	ConnectionId string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ExternalId   string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // upstream id, e.g. arr movie/series id
	// raw upstream status passed through for display; status is the
	// host-normalized value
	ExternalStatus string `protobuf:"bytes,4,opt,name=external_status,json=externalStatus,proto3" json:"external_status,omitempty"`
	// host-normalized: "queued" | "downloading" | "completed" | "failed"
	Status  string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// wording describes this target to requesters, in place of the manifest's
	// wording for its status; see TargetStatus.wording.
	Wording       *RequestStatusWording `protobuf:"bytes,7,opt,name=wording,proto3" json:"wording,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillmentTarget) Reset() {
	*x = FulfillmentTarget{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillmentTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillmentTarget) ProtoMessage() {}

func (x *FulfillmentTarget) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillmentTarget.ProtoReflect.Descriptor instead.
func (*FulfillmentTarget) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{7}
}

func (x *FulfillmentTarget) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *FulfillmentTarget) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *FulfillmentTarget) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FulfillmentTarget) GetExternalStatus() string {
	if x != nil {
		return x.ExternalStatus
	}
	return ""
}

func (x *FulfillmentTarget) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FulfillmentTarget) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FulfillmentTarget) GetWording() *RequestStatusWording {
	if x != nil {
		return x.Wording
	}
	return nil
}

type FulfillResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Targets []*FulfillmentTarget   `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// set when zero targets, e.g. "no radarr instance configured"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillResponse) Reset() {
	*x = FulfillResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillResponse) ProtoMessage() {}

func (x *FulfillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillResponse.ProtoReflect.Descriptor instead.
func (*FulfillResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{8}
}

func (x *FulfillResponse) GetTargets() []*FulfillmentTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *FulfillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRef) Reset() {
	*x = TargetRef{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRef) ProtoMessage() {}

func (x *TargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRef.ProtoReflect.Descriptor instead.
func (*TargetRef) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{9}
}

func (x *TargetRef) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *TargetRef) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TargetRef) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type CheckStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Request       *RequestDescriptor     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Targets       []*TargetRef           `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Connections   []*RouterConnection    `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusRequest) Reset() {
	*x = CheckStatusRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusRequest) ProtoMessage() {}

func (x *CheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{10}
}

func (x *CheckStatusRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *CheckStatusRequest) GetRequest() *RequestDescriptor {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CheckStatusRequest) GetTargets() []*TargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CheckStatusRequest) GetConnections() []*RouterConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

// DownloadProgress is how far a target's downloads are, as the downstream
// service reports them. Set only while the target is queued or downloading and
// the service has something in its download queue for it.
type DownloadProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host-normalized: "queued" | "downloading" | "paused" | "stalled" |
	// "importing" | "import_blocked". Required whenever progress is set: hosts
	// count a progress with an empty phase and a bytes_total of 0 as unset. A
	// target with several downloads reports the phase that ranks first in
	// import_blocked > stalled > downloading > importing > paused > queued.
	// Hosts treat unknown values as downloading.
	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// Summed over the target's distinct downloads (a season pack counts once).
	// 0 whenever any of those downloads has an unknown size, so the host shows
	// no percentage rather than an overstated one.
	BytesTotal int64 `protobuf:"varint,2,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	// What remains of bytes_total, from 0 to bytes_total; 0 whenever
	// bytes_total is 0.
	BytesLeft int64 `protobuf:"varint,3,opt,name=bytes_left,json=bytesLeft,proto3" json:"bytes_left,omitempty"`
	// Latest estimated completion across the downloads; unset when unknown.
	EstimatedCompletion *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=estimated_completion,json=estimatedCompletion,proto3" json:"estimated_completion,omitempty"`
	// Distinct downloads in flight for the target.
	Downloads     int32 `protobuf:"varint,5,opt,name=downloads,proto3" json:"downloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadProgress) Reset() {
	*x = DownloadProgress{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgress) ProtoMessage() {}

func (x *DownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgress.ProtoReflect.Descriptor instead.
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DownloadProgress) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *DownloadProgress) GetBytesLeft() int64 {
	if x != nil {
		return x.BytesLeft
	}
	return 0
}

func (x *DownloadProgress) GetEstimatedCompletion() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedCompletion
	}
	return nil
}

func (x *DownloadProgress) GetDownloads() int32 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

type TargetStatus struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Quality      string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	ConnectionId string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// host-normalized: "queued" | "downloading" | "completed" | "failed"
	Status         string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExternalStatus string `protobuf:"bytes,4,opt,name=external_status,json=externalStatus,proto3" json:"external_status,omitempty"` // raw upstream status passed through for display
	Message        string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// progress is filled by plugins that declare
	// RequestRouterDescriptor.reports_download_progress; hosts ignore it from
	// other plugins. The host first sees it on its regular reconcile pass, then
	// checks the target every minute while progress is set and the target is
	// downloading. Leaving it unset, or setting it with an empty phase and a
	// bytes_total of 0, means nothing is in flight: the host clears the progress
	// it last stored and checks the target on its regular reconcile cadence
	// again.
	Progress *DownloadProgress `protobuf:"bytes,6,opt,name=progress,proto3" json:"progress,omitempty"`
	// wording describes where this target is, for everyone who can see the
	// request, when the plugin knows more than its status says: e.g. label
	// "Not out yet", detail "Radarr adds it once it's out, expected
	// December 18, 2026." It replaces the manifest's wording for the target's
	// status (RequestRouterWording.queued or .downloading): a label replaces
	// both the label and the detail, and a detail alone replaces only the
	// detail. Set it only while the status is queued or downloading. Each
	// answer replaces the last, so leave it unset once it no longer applies.
	// The same limits apply as to the manifest's wording, and hosts drop
	// wording that breaks them. Never include release names, indexers,
	// download clients or paths.
	Wording       *RequestStatusWording `protobuf:"bytes,7,opt,name=wording,proto3" json:"wording,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetStatus) Reset() {
	*x = TargetStatus{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatus) ProtoMessage() {}

func (x *TargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatus.ProtoReflect.Descriptor instead.
func (*TargetStatus) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{12}
}

func (x *TargetStatus) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *TargetStatus) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TargetStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TargetStatus) GetExternalStatus() string {
	if x != nil {
		return x.ExternalStatus
	}
	return ""
}

func (x *TargetStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TargetStatus) GetProgress() *DownloadProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *TargetStatus) GetWording() *RequestStatusWording {
	if x != nil {
		return x.Wording
	}
	return nil
}

type CheckStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TargetStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{13}
}

func (x *CheckStatusResponse) GetStatuses() []*TargetStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ConfigOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigOption) Reset() {
	*x = ConfigOption{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigOption) ProtoMessage() {}

func (x *ConfigOption) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigOption.ProtoReflect.Descriptor instead.
func (*ConfigOption) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ConfigOptionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*ConfigOption        `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigOptionList) Reset() {
	*x = ConfigOptionList{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigOptionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigOptionList) ProtoMessage() {}

func (x *ConfigOptionList) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigOptionList.ProtoReflect.Descriptor instead.
func (*ConfigOptionList) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigOptionList) GetOptions() []*ConfigOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListConfigOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Connection    *RouterConnection      `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigOptionsRequest) Reset() {
	*x = ListConfigOptionsRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigOptionsRequest) ProtoMessage() {}

func (x *ListConfigOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigOptionsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{16}
}

func (x *ListConfigOptionsRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ListConfigOptionsRequest) GetConnection() *RouterConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type ListConfigOptionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keyed by config field, e.g. "root_folder"
	OptionsByField map[string]*ConfigOptionList `protobuf:"bytes,1,rep,name=options_by_field,json=optionsByField,proto3" json:"options_by_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConfigOptionsResponse) Reset() {
	*x = ListConfigOptionsResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigOptionsResponse) ProtoMessage() {}

func (x *ListConfigOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigOptionsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{17}
}

func (x *ListConfigOptionsResponse) GetOptionsByField() map[string]*ConfigOptionList {
	if x != nil {
		return x.OptionsByField
	}
	return nil
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Connection    *RouterConnection      `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{18}
}

func (x *TestConnectionRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *TestConnectionRequest) GetConnection() *RouterConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{19}
}

func (x *TestConnectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Connection   *RouterConnection      `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// siblings are the other connections bound to this installation+capability, so
	// a plugin can enforce cross-connection rules (e.g. one default per service
	// type). They carry id + config only — no base_url/api_key (validation reads
	// flags, not credentials).
	Siblings      []*RouterConnection `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{20}
}

func (x *ValidateRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ValidateRequest) GetConnection() *RouterConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ValidateRequest) GetSiblings() []*RouterConnection {
	if x != nil {
		return x.Siblings
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldErrors   map[string]string      `protobuf:"bytes,1,rep,name=field_errors,json=fieldErrors,proto3" json:"field_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // keyed by config field; empty = no field errors
	FormError     string                 `protobuf:"bytes,2,opt,name=form_error,json=formError,proto3" json:"form_error,omitempty"`                                                                                 // form-level error; empty = none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{21}
}

func (x *ValidateResponse) GetFieldErrors() map[string]string {
	if x != nil {
		return x.FieldErrors
	}
	return nil
}

func (x *ValidateResponse) GetFormError() string {
	if x != nil {
		return x.FormError
	}
	return ""
}

var File_silo_plugin_v1_request_router_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_request_router_proto_rawDesc = "" +
	"\n" +
	"#silo/plugin/v1/request_router.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x03\n" +
	"\x11RequestDescriptor\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12U\n" +
	"\fexternal_ids\x18\x04 \x03(\v22.silo.plugin.v1.RequestDescriptor.ExternalIdsEntryR\vexternalIds\x12\x19\n" +
	"\bis_anime\x18\x05 \x01(\bR\aisAnime\x12*\n" +
	"\x11requester_user_id\x18\x06 \x01(\x03R\x0frequesterUserId\x120\n" +
	"\x14requester_profile_id\x18\a \x01(\tR\x12requesterProfileId\x12'\n" +
	"\x0frequester_email\x18\b \x01(\tR\x0erequesterEmail\x12-\n" +
	"\x12requester_username\x18\t \x01(\tR\x11requesterUsername\x12\x18\n" +
	"\aseasons\x18\n" +
	" \x03(\x05R\aseasons\x1a>\n" +
	"\x10ExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x17RequestRouterDescriptor\x12)\n" +
	"\x10supports_seasons\x18\x01 \x01(\bR\x0fsupportsSeasons\x12:\n" +
	"\x19reports_download_progress\x18\x02 \x01(\bR\x17reportsDownloadProgress\x12>\n" +
	"\awording\x18\x03 \x01(\v2$.silo.plugin.v1.RequestRouterWordingR\awording\"\xb0\x01\n" +
	"\x14RequestRouterWording\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12<\n" +
	"\x06queued\x18\x02 \x01(\v2$.silo.plugin.v1.RequestStatusWordingR\x06queued\x12F\n" +
	"\vdownloading\x18\x03 \x01(\v2$.silo.plugin.v1.RequestStatusWordingR\vdownloading\"D\n" +
	"\x14RequestStatusWording\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x87\x01\n" +
	"\x10RouterConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\"6\n" +
	"\x10RequestedQuality\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04is4k\x18\x02 \x01(\bR\x04is4k\"\xf6\x01\n" +
	"\x0eFulfillRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12;\n" +
	"\arequest\x18\x02 \x01(\v2!.silo.plugin.v1.RequestDescriptorR\arequest\x12>\n" +
	"\tqualities\x18\x03 \x03(\v2 .silo.plugin.v1.RequestedQualityR\tqualities\x12B\n" +
	"\vconnections\x18\x04 \x03(\v2 .silo.plugin.v1.RouterConnectionR\vconnections\"\x8e\x02\n" +
	"\x11FulfillmentTarget\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12'\n" +
	"\x0fexternal_status\x18\x04 \x01(\tR\x0eexternalStatus\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12>\n" +
	"\awording\x18\a \x01(\v2$.silo.plugin.v1.RequestStatusWordingR\awording\"h\n" +
	"\x0fFulfillResponse\x12;\n" +
	"\atargets\x18\x01 \x03(\v2!.silo.plugin.v1.FulfillmentTargetR\atargets\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\tTargetRef\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\"\xef\x01\n" +
	"\x12CheckStatusRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12;\n" +
	"\arequest\x18\x02 \x01(\v2!.silo.plugin.v1.RequestDescriptorR\arequest\x123\n" +
	"\atargets\x18\x03 \x03(\v2\x19.silo.plugin.v1.TargetRefR\atargets\x12B\n" +
	"\vconnections\x18\x04 \x03(\v2 .silo.plugin.v1.RouterConnectionR\vconnections\"\xd5\x01\n" +
	"\x10DownloadProgress\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1f\n" +
	"\vbytes_total\x18\x02 \x01(\x03R\n" +
	"bytesTotal\x12\x1d\n" +
	"\n" +
	"bytes_left\x18\x03 \x01(\x03R\tbytesLeft\x12M\n" +
	"\x14estimated_completion\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedCompletion\x12\x1c\n" +
	"\tdownloads\x18\x05 \x01(\x05R\tdownloads\"\xa6\x02\n" +
	"\fTargetStatus\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fexternal_status\x18\x04 \x01(\tR\x0eexternalStatus\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12<\n" +
	"\bprogress\x18\x06 \x01(\v2 .silo.plugin.v1.DownloadProgressR\bprogress\x12>\n" +
	"\awording\x18\a \x01(\v2$.silo.plugin.v1.RequestStatusWordingR\awording\"O\n" +
	"\x13CheckStatusResponse\x128\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1c.silo.plugin.v1.TargetStatusR\bstatuses\":\n" +
	"\fConfigOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"J\n" +
	"\x10ConfigOptionList\x126\n" +
	"\aoptions\x18\x01 \x03(\v2\x1c.silo.plugin.v1.ConfigOptionR\aoptions\"\x81\x01\n" +
	"\x18ListConfigOptionsRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12@\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2 .silo.plugin.v1.RouterConnectionR\n" +
	"connection\"\xe9\x01\n" +
	"\x19ListConfigOptionsResponse\x12g\n" +
	"\x10options_by_field\x18\x01 \x03(\v2=.silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntryR\x0eoptionsByField\x1ac\n" +
	"\x13OptionsByFieldEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .silo.plugin.v1.ConfigOptionListR\x05value:\x028\x01\"~\n" +
	"\x15TestConnectionRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12@\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2 .silo.plugin.v1.RouterConnectionR\n" +
	"connection\"B\n" +
	"\x16TestConnectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb6\x01\n" +
	"\x0fValidateRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12@\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2 .silo.plugin.v1.RouterConnectionR\n" +
	"connection\x12<\n" +
	"\bsiblings\x18\x03 \x03(\v2 .silo.plugin.v1.RouterConnectionR\bsiblings\"\xc7\x01\n" +
	"\x10ValidateResponse\x12T\n" +
	"\ffield_errors\x18\x01 \x03(\v21.silo.plugin.v1.ValidateResponse.FieldErrorsEntryR\vfieldErrors\x12\x1d\n" +
	"\n" +
	"form_error\x18\x02 \x01(\tR\tformError\x1a>\n" +
	"\x10FieldErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcd\x03\n" +
	"\rRequestRouter\x12J\n" +
	"\aFulfill\x12\x1e.silo.plugin.v1.FulfillRequest\x1a\x1f.silo.plugin.v1.FulfillResponse\x12V\n" +
	"\vCheckStatus\x12\".silo.plugin.v1.CheckStatusRequest\x1a#.silo.plugin.v1.CheckStatusResponse\x12h\n" +
	"\x11ListConfigOptions\x12(.silo.plugin.v1.ListConfigOptionsRequest\x1a).silo.plugin.v1.ListConfigOptionsResponse\x12_\n" +
	"\x0eTestConnection\x12%.silo.plugin.v1.TestConnectionRequest\x1a&.silo.plugin.v1.TestConnectionResponse\x12M\n" +
	"\bValidate\x12\x1f.silo.plugin.v1.ValidateRequest\x1a .silo.plugin.v1.ValidateResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_request_router_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_request_router_proto_rawDescData []byte
)

func file_silo_plugin_v1_request_router_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_request_router_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_request_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_request_router_proto_rawDesc), len(file_silo_plugin_v1_request_router_proto_rawDesc)))
	})
	return file_silo_plugin_v1_request_router_proto_rawDescData
}

var file_silo_plugin_v1_request_router_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_silo_plugin_v1_request_router_proto_goTypes = []any{
	(*RequestDescriptor)(nil),         // 0: silo.plugin.v1.RequestDescriptor
	(*RequestRouterDescriptor)(nil),   // 1: silo.plugin.v1.RequestRouterDescriptor
	(*RequestRouterWording)(nil),      // 2: silo.plugin.v1.RequestRouterWording
	(*RequestStatusWording)(nil),      // 3: silo.plugin.v1.RequestStatusWording
	(*RouterConnection)(nil),          // 4: silo.plugin.v1.RouterConnection
	(*RequestedQuality)(nil),          // 5: silo.plugin.v1.RequestedQuality
	(*FulfillRequest)(nil),            // 6: silo.plugin.v1.FulfillRequest
	(*FulfillmentTarget)(nil),         // 7: silo.plugin.v1.FulfillmentTarget
	(*FulfillResponse)(nil),           // 8: silo.plugin.v1.FulfillResponse
	(*TargetRef)(nil),                 // 9: silo.plugin.v1.TargetRef
	(*CheckStatusRequest)(nil),        // 10: silo.plugin.v1.CheckStatusRequest
	(*DownloadProgress)(nil),          // 11: silo.plugin.v1.DownloadProgress
	(*TargetStatus)(nil),              // 12: silo.plugin.v1.TargetStatus
	(*CheckStatusResponse)(nil),       // 13: silo.plugin.v1.CheckStatusResponse
	(*ConfigOption)(nil),              // 14: silo.plugin.v1.ConfigOption
	(*ConfigOptionList)(nil),          // 15: silo.plugin.v1.ConfigOptionList
	(*ListConfigOptionsRequest)(nil),  // 16: silo.plugin.v1.ListConfigOptionsRequest
	(*ListConfigOptionsResponse)(nil), // 17: silo.plugin.v1.ListConfigOptionsResponse
	(*TestConnectionRequest)(nil),     // 18: silo.plugin.v1.TestConnectionRequest
	(*TestConnectionResponse)(nil),    // 19: silo.plugin.v1.TestConnectionResponse
	(*ValidateRequest)(nil),           // 20: silo.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil),          // 21: silo.plugin.v1.ValidateResponse
	nil,                               // 22: silo.plugin.v1.RequestDescriptor.ExternalIdsEntry
	nil,                               // 23: silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntry
	nil,                               // 24: silo.plugin.v1.ValidateResponse.FieldErrorsEntry
	(*structpb.Struct)(nil),           // 25: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_silo_plugin_v1_request_router_proto_depIdxs = []int32{
	22, // 0: silo.plugin.v1.RequestDescriptor.external_ids:type_name -> silo.plugin.v1.RequestDescriptor.ExternalIdsEntry
	2,  // 1: silo.plugin.v1.RequestRouterDescriptor.wording:type_name -> silo.plugin.v1.RequestRouterWording
	3,  // 2: silo.plugin.v1.RequestRouterWording.queued:type_name -> silo.plugin.v1.RequestStatusWording
	3,  // 3: silo.plugin.v1.RequestRouterWording.downloading:type_name -> silo.plugin.v1.RequestStatusWording
	25, // 4: silo.plugin.v1.RouterConnection.config:type_name -> google.protobuf.Struct
	0,  // 5: silo.plugin.v1.FulfillRequest.request:type_name -> silo.plugin.v1.RequestDescriptor
	5,  // 6: silo.plugin.v1.FulfillRequest.qualities:type_name -> silo.plugin.v1.RequestedQuality
	4,  // 7: silo.plugin.v1.FulfillRequest.connections:type_name -> silo.plugin.v1.RouterConnection
	3,  // 8: silo.plugin.v1.FulfillmentTarget.wording:type_name -> silo.plugin.v1.RequestStatusWording
	7,  // 9: silo.plugin.v1.FulfillResponse.targets:type_name -> silo.plugin.v1.FulfillmentTarget
	0,  // 10: silo.plugin.v1.CheckStatusRequest.request:type_name -> silo.plugin.v1.RequestDescriptor
	9,  // 11: silo.plugin.v1.CheckStatusRequest.targets:type_name -> silo.plugin.v1.TargetRef
	4,  // 12: silo.plugin.v1.CheckStatusRequest.connections:type_name -> silo.plugin.v1.RouterConnection
	26, // 13: silo.plugin.v1.DownloadProgress.estimated_completion:type_name -> google.protobuf.Timestamp
	11, // 14: silo.plugin.v1.TargetStatus.progress:type_name -> silo.plugin.v1.DownloadProgress
	3,  // 15: silo.plugin.v1.TargetStatus.wording:type_name -> silo.plugin.v1.RequestStatusWording
	12, // 16: silo.plugin.v1.CheckStatusResponse.statuses:type_name -> silo.plugin.v1.TargetStatus
	14, // 17: silo.plugin.v1.ConfigOptionList.options:type_name -> silo.plugin.v1.ConfigOption
	4,  // 18: silo.plugin.v1.ListConfigOptionsRequest.connection:type_name -> silo.plugin.v1.RouterConnection
	23, // 19: silo.plugin.v1.ListConfigOptionsResponse.options_by_field:type_name -> silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntry
	4,  // 20: silo.plugin.v1.TestConnectionRequest.connection:type_name -> silo.plugin.v1.RouterConnection
	4,  // 21: silo.plugin.v1.ValidateRequest.connection:type_name -> silo.plugin.v1.RouterConnection
	4,  // 22: silo.plugin.v1.ValidateRequest.siblings:type_name -> silo.plugin.v1.RouterConnection
	24, // 23: silo.plugin.v1.ValidateResponse.field_errors:type_name -> silo.plugin.v1.ValidateResponse.FieldErrorsEntry
	15, // 24: silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntry.value:type_name -> silo.plugin.v1.ConfigOptionList
	6,  // 25: silo.plugin.v1.RequestRouter.Fulfill:input_type -> silo.plugin.v1.FulfillRequest
	10, // 26: silo.plugin.v1.RequestRouter.CheckStatus:input_type -> silo.plugin.v1.CheckStatusRequest
	16, // 27: silo.plugin.v1.RequestRouter.ListConfigOptions:input_type -> silo.plugin.v1.ListConfigOptionsRequest
	18, // 28: silo.plugin.v1.RequestRouter.TestConnection:input_type -> silo.plugin.v1.TestConnectionRequest
	20, // 29: silo.plugin.v1.RequestRouter.Validate:input_type -> silo.plugin.v1.ValidateRequest
	8,  // 30: silo.plugin.v1.RequestRouter.Fulfill:output_type -> silo.plugin.v1.FulfillResponse
	13, // 31: silo.plugin.v1.RequestRouter.CheckStatus:output_type -> silo.plugin.v1.CheckStatusResponse
	17, // 32: silo.plugin.v1.RequestRouter.ListConfigOptions:output_type -> silo.plugin.v1.ListConfigOptionsResponse
	19, // 33: silo.plugin.v1.RequestRouter.TestConnection:output_type -> silo.plugin.v1.TestConnectionResponse
	21, // 34: silo.plugin.v1.RequestRouter.Validate:output_type -> silo.plugin.v1.ValidateResponse
	30, // [30:35] is the sub-list for method output_type
	25, // [25:30] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_request_router_proto_init() }
func file_silo_plugin_v1_request_router_proto_init() {
	if File_silo_plugin_v1_request_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_request_router_proto_rawDesc), len(file_silo_plugin_v1_request_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_request_router_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_request_router_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_request_router_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_request_router_proto = out.File
	file_silo_plugin_v1_request_router_proto_goTypes = nil
	file_silo_plugin_v1_request_router_proto_depIdxs = nil
}
