// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/scan_source.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollChangesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which configured scan_source capability instance is being polled.
	CapabilityId string `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	// Opaque continuation token from the previous PollChanges. Empty on first
	// run, which the provider treats as "start from now" (do not replay history).
	Marker string `protobuf:"bytes,2,opt,name=marker,proto3" json:"marker,omitempty"`
	// Resolved upstream connection for this source. The host resolves the
	// operator's connection config (own credentials, or a reused link) and passes
	// the concrete values here each poll, so the plugin stays credential-source
	// agnostic and never stores secrets at rest. Delivered over the local
	// host<->plugin gRPC channel only.
	Connection    *ResolvedConnection `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollChangesRequest) Reset() {
	*x = PollChangesRequest{}
	mi := &file_silo_plugin_v1_scan_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollChangesRequest) ProtoMessage() {}

func (x *PollChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_scan_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollChangesRequest.ProtoReflect.Descriptor instead.
func (*PollChangesRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_scan_source_proto_rawDescGZIP(), []int{0}
}

func (x *PollChangesRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *PollChangesRequest) GetMarker() string {
	if x != nil {
		return x.Marker
	}
	return ""
}

func (x *PollChangesRequest) GetConnection() *ResolvedConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

// ResolvedConnection carries the concrete upstream credentials the plugin needs
// to reach its source (e.g. a Sonarr/Radarr base URL + API key).
type ResolvedConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedConnection) Reset() {
	*x = ResolvedConnection{}
	mi := &file_silo_plugin_v1_scan_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedConnection) ProtoMessage() {}

func (x *ResolvedConnection) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_scan_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedConnection.ProtoReflect.Descriptor instead.
func (*ResolvedConnection) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_scan_source_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvedConnection) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ResolvedConnection) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type PollChangesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute paths already translated into Silo's filesystem namespace (the
	// plugin has applied its own path rewrites). Files or directories.
	ChangedPaths []string `protobuf:"bytes,1,rep,name=changed_paths,json=changedPaths,proto3" json:"changed_paths,omitempty"`
	// Opaque continuation token. The host stores it verbatim and echoes it back
	// on the next PollChanges; the host never parses it.
	NextMarker    string `protobuf:"bytes,2,opt,name=next_marker,json=nextMarker,proto3" json:"next_marker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollChangesResponse) Reset() {
	*x = PollChangesResponse{}
	mi := &file_silo_plugin_v1_scan_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollChangesResponse) ProtoMessage() {}

func (x *PollChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_scan_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollChangesResponse.ProtoReflect.Descriptor instead.
func (*PollChangesResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_scan_source_proto_rawDescGZIP(), []int{2}
}

func (x *PollChangesResponse) GetChangedPaths() []string {
	if x != nil {
		return x.ChangedPaths
	}
	return nil
}

func (x *PollChangesResponse) GetNextMarker() string {
	if x != nil {
		return x.NextMarker
	}
	return ""
}

var File_silo_plugin_v1_scan_source_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_scan_source_proto_rawDesc = "" +
	"\n" +
	" silo/plugin/v1/scan_source.proto\x12\x0esilo.plugin.v1\"\x95\x01\n" +
	"\x12PollChangesRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12\x16\n" +
	"\x06marker\x18\x02 \x01(\tR\x06marker\x12B\n" +
	"\n" +
	"connection\x18\x03 \x01(\v2\".silo.plugin.v1.ResolvedConnectionR\n" +
	"connection\"H\n" +
	"\x12ResolvedConnection\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"[\n" +
	"\x13PollChangesResponse\x12#\n" +
	"\rchanged_paths\x18\x01 \x03(\tR\fchangedPaths\x12\x1f\n" +
	"\vnext_marker\x18\x02 \x01(\tR\n" +
	"nextMarker2d\n" +
	"\n" +
	"ScanSource\x12V\n" +
	"\vPollChanges\x12\".silo.plugin.v1.PollChangesRequest\x1a#.silo.plugin.v1.PollChangesResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_scan_source_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_scan_source_proto_rawDescData []byte
)

func file_silo_plugin_v1_scan_source_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_scan_source_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_scan_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_scan_source_proto_rawDesc), len(file_silo_plugin_v1_scan_source_proto_rawDesc)))
	})
	return file_silo_plugin_v1_scan_source_proto_rawDescData
}

var file_silo_plugin_v1_scan_source_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_silo_plugin_v1_scan_source_proto_goTypes = []any{
	(*PollChangesRequest)(nil),  // 0: silo.plugin.v1.PollChangesRequest
	(*ResolvedConnection)(nil),  // 1: silo.plugin.v1.ResolvedConnection
	(*PollChangesResponse)(nil), // 2: silo.plugin.v1.PollChangesResponse
}
var file_silo_plugin_v1_scan_source_proto_depIdxs = []int32{
	1, // 0: silo.plugin.v1.PollChangesRequest.connection:type_name -> silo.plugin.v1.ResolvedConnection
	0, // 1: silo.plugin.v1.ScanSource.PollChanges:input_type -> silo.plugin.v1.PollChangesRequest
	2, // 2: silo.plugin.v1.ScanSource.PollChanges:output_type -> silo.plugin.v1.PollChangesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_scan_source_proto_init() }
func file_silo_plugin_v1_scan_source_proto_init() {
	if File_silo_plugin_v1_scan_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_scan_source_proto_rawDesc), len(file_silo_plugin_v1_scan_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_scan_source_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_scan_source_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_scan_source_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_scan_source_proto = out.File
	file_silo_plugin_v1_scan_source_proto_goTypes = nil
	file_silo_plugin_v1_scan_source_proto_depIdxs = nil
}
