// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/watch_sync_provider.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchSyncAuthMethod int32

const (
	WatchSyncAuthMethod_WATCH_SYNC_AUTH_METHOD_UNSPECIFIED        WatchSyncAuthMethod = 0
	WatchSyncAuthMethod_WATCH_SYNC_AUTH_METHOD_AUTHORIZATION_CODE WatchSyncAuthMethod = 1
	WatchSyncAuthMethod_WATCH_SYNC_AUTH_METHOD_API_KEY            WatchSyncAuthMethod = 2
)

// Enum value maps for WatchSyncAuthMethod.
var (
	WatchSyncAuthMethod_name = map[int32]string{
		0: "WATCH_SYNC_AUTH_METHOD_UNSPECIFIED",
		1: "WATCH_SYNC_AUTH_METHOD_AUTHORIZATION_CODE",
		2: "WATCH_SYNC_AUTH_METHOD_API_KEY",
	}
	WatchSyncAuthMethod_value = map[string]int32{
		"WATCH_SYNC_AUTH_METHOD_UNSPECIFIED":        0,
		"WATCH_SYNC_AUTH_METHOD_AUTHORIZATION_CODE": 1,
		"WATCH_SYNC_AUTH_METHOD_API_KEY":            2,
	}
)

func (x WatchSyncAuthMethod) Enum() *WatchSyncAuthMethod {
	p := new(WatchSyncAuthMethod)
	*p = x
	return p
}

func (x WatchSyncAuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSyncAuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[0].Descriptor()
}

func (WatchSyncAuthMethod) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[0]
}

func (x WatchSyncAuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSyncAuthMethod.Descriptor instead.
func (WatchSyncAuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{0}
}

type WatchSyncOperation int32

const (
	WatchSyncOperation_WATCH_SYNC_OPERATION_UNSPECIFIED    WatchSyncOperation = 0
	WatchSyncOperation_WATCH_SYNC_OPERATION_MARK_WATCHED   WatchSyncOperation = 1
	WatchSyncOperation_WATCH_SYNC_OPERATION_MARK_UNWATCHED WatchSyncOperation = 2
)

// Enum value maps for WatchSyncOperation.
var (
	WatchSyncOperation_name = map[int32]string{
		0: "WATCH_SYNC_OPERATION_UNSPECIFIED",
		1: "WATCH_SYNC_OPERATION_MARK_WATCHED",
		2: "WATCH_SYNC_OPERATION_MARK_UNWATCHED",
	}
	WatchSyncOperation_value = map[string]int32{
		"WATCH_SYNC_OPERATION_UNSPECIFIED":    0,
		"WATCH_SYNC_OPERATION_MARK_WATCHED":   1,
		"WATCH_SYNC_OPERATION_MARK_UNWATCHED": 2,
	}
)

func (x WatchSyncOperation) Enum() *WatchSyncOperation {
	p := new(WatchSyncOperation)
	*p = x
	return p
}

func (x WatchSyncOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSyncOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[1].Descriptor()
}

func (WatchSyncOperation) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[1]
}

func (x WatchSyncOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSyncOperation.Descriptor instead.
func (WatchSyncOperation) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{1}
}

type WatchSyncOrigin int32

const (
	WatchSyncOrigin_WATCH_SYNC_ORIGIN_UNSPECIFIED         WatchSyncOrigin = 0
	WatchSyncOrigin_WATCH_SYNC_ORIGIN_PLAYBACK_COMPLETION WatchSyncOrigin = 1
	WatchSyncOrigin_WATCH_SYNC_ORIGIN_MANUAL              WatchSyncOrigin = 2
	WatchSyncOrigin_WATCH_SYNC_ORIGIN_RECONCILIATION      WatchSyncOrigin = 3
)

// Enum value maps for WatchSyncOrigin.
var (
	WatchSyncOrigin_name = map[int32]string{
		0: "WATCH_SYNC_ORIGIN_UNSPECIFIED",
		1: "WATCH_SYNC_ORIGIN_PLAYBACK_COMPLETION",
		2: "WATCH_SYNC_ORIGIN_MANUAL",
		3: "WATCH_SYNC_ORIGIN_RECONCILIATION",
	}
	WatchSyncOrigin_value = map[string]int32{
		"WATCH_SYNC_ORIGIN_UNSPECIFIED":         0,
		"WATCH_SYNC_ORIGIN_PLAYBACK_COMPLETION": 1,
		"WATCH_SYNC_ORIGIN_MANUAL":              2,
		"WATCH_SYNC_ORIGIN_RECONCILIATION":      3,
	}
)

func (x WatchSyncOrigin) Enum() *WatchSyncOrigin {
	p := new(WatchSyncOrigin)
	*p = x
	return p
}

func (x WatchSyncOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSyncOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[2].Descriptor()
}

func (WatchSyncOrigin) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[2]
}

func (x WatchSyncOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSyncOrigin.Descriptor instead.
func (WatchSyncOrigin) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{2}
}

type WatchSyncApplyStatus int32

const (
	WatchSyncApplyStatus_WATCH_SYNC_APPLY_STATUS_UNSPECIFIED WatchSyncApplyStatus = 0
	WatchSyncApplyStatus_WATCH_SYNC_APPLY_STATUS_APPLIED     WatchSyncApplyStatus = 1
	WatchSyncApplyStatus_WATCH_SYNC_APPLY_STATUS_NO_CHANGE   WatchSyncApplyStatus = 2
	WatchSyncApplyStatus_WATCH_SYNC_APPLY_STATUS_RETRY       WatchSyncApplyStatus = 3
	WatchSyncApplyStatus_WATCH_SYNC_APPLY_STATUS_REJECTED    WatchSyncApplyStatus = 4
)

// Enum value maps for WatchSyncApplyStatus.
var (
	WatchSyncApplyStatus_name = map[int32]string{
		0: "WATCH_SYNC_APPLY_STATUS_UNSPECIFIED",
		1: "WATCH_SYNC_APPLY_STATUS_APPLIED",
		2: "WATCH_SYNC_APPLY_STATUS_NO_CHANGE",
		3: "WATCH_SYNC_APPLY_STATUS_RETRY",
		4: "WATCH_SYNC_APPLY_STATUS_REJECTED",
	}
	WatchSyncApplyStatus_value = map[string]int32{
		"WATCH_SYNC_APPLY_STATUS_UNSPECIFIED": 0,
		"WATCH_SYNC_APPLY_STATUS_APPLIED":     1,
		"WATCH_SYNC_APPLY_STATUS_NO_CHANGE":   2,
		"WATCH_SYNC_APPLY_STATUS_RETRY":       3,
		"WATCH_SYNC_APPLY_STATUS_REJECTED":    4,
	}
)

func (x WatchSyncApplyStatus) Enum() *WatchSyncApplyStatus {
	p := new(WatchSyncApplyStatus)
	*p = x
	return p
}

func (x WatchSyncApplyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSyncApplyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[3].Descriptor()
}

func (WatchSyncApplyStatus) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[3]
}

func (x WatchSyncApplyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSyncApplyStatus.Descriptor instead.
func (WatchSyncApplyStatus) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{3}
}

type WatchSyncFaultCode int32

const (
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_UNSPECIFIED        WatchSyncFaultCode = 0
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_TEMPORARY          WatchSyncFaultCode = 1
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_RATE_LIMITED       WatchSyncFaultCode = 2
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_INVALID_CREDENTIAL WatchSyncFaultCode = 3
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_PERMISSION_DENIED  WatchSyncFaultCode = 4
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_INVALID_REQUEST    WatchSyncFaultCode = 5
	WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_PERMANENT          WatchSyncFaultCode = 6
)

// Enum value maps for WatchSyncFaultCode.
var (
	WatchSyncFaultCode_name = map[int32]string{
		0: "WATCH_SYNC_FAULT_CODE_UNSPECIFIED",
		1: "WATCH_SYNC_FAULT_CODE_TEMPORARY",
		2: "WATCH_SYNC_FAULT_CODE_RATE_LIMITED",
		3: "WATCH_SYNC_FAULT_CODE_INVALID_CREDENTIAL",
		4: "WATCH_SYNC_FAULT_CODE_PERMISSION_DENIED",
		5: "WATCH_SYNC_FAULT_CODE_INVALID_REQUEST",
		6: "WATCH_SYNC_FAULT_CODE_PERMANENT",
	}
	WatchSyncFaultCode_value = map[string]int32{
		"WATCH_SYNC_FAULT_CODE_UNSPECIFIED":        0,
		"WATCH_SYNC_FAULT_CODE_TEMPORARY":          1,
		"WATCH_SYNC_FAULT_CODE_RATE_LIMITED":       2,
		"WATCH_SYNC_FAULT_CODE_INVALID_CREDENTIAL": 3,
		"WATCH_SYNC_FAULT_CODE_PERMISSION_DENIED":  4,
		"WATCH_SYNC_FAULT_CODE_INVALID_REQUEST":    5,
		"WATCH_SYNC_FAULT_CODE_PERMANENT":          6,
	}
)

func (x WatchSyncFaultCode) Enum() *WatchSyncFaultCode {
	p := new(WatchSyncFaultCode)
	*p = x
	return p
}

func (x WatchSyncFaultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSyncFaultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[4].Descriptor()
}

func (WatchSyncFaultCode) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_watch_sync_provider_proto_enumTypes[4]
}

func (x WatchSyncFaultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSyncFaultCode.Descriptor instead.
func (WatchSyncFaultCode) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{4}
}

type WatchSyncProviderDescriptor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AuthMethods          []WatchSyncAuthMethod  `protobuf:"varint,1,rep,packed,name=auth_methods,json=authMethods,proto3,enum=silo.plugin.v1.WatchSyncAuthMethod" json:"auth_methods,omitempty"`
	ExportWatched        bool                   `protobuf:"varint,2,opt,name=export_watched,json=exportWatched,proto3" json:"export_watched,omitempty"`
	ExportUnwatched      bool                   `protobuf:"varint,3,opt,name=export_unwatched,json=exportUnwatched,proto3" json:"export_unwatched,omitempty"`
	ImportWatched        bool                   `protobuf:"varint,4,opt,name=import_watched,json=importWatched,proto3" json:"import_watched,omitempty"`
	ImportProgress       bool                   `protobuf:"varint,5,opt,name=import_progress,json=importProgress,proto3" json:"import_progress,omitempty"`
	SupportedMediaTypes  []string               `protobuf:"bytes,6,rep,name=supported_media_types,json=supportedMediaTypes,proto3" json:"supported_media_types,omitempty"`
	ExternalIdNamespaces []string               `protobuf:"bytes,7,rep,name=external_id_namespaces,json=externalIdNamespaces,proto3" json:"external_id_namespaces,omitempty"`
	MaxBatchSize         int32                  `protobuf:"varint,8,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WatchSyncProviderDescriptor) Reset() {
	*x = WatchSyncProviderDescriptor{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncProviderDescriptor) ProtoMessage() {}

func (x *WatchSyncProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncProviderDescriptor.ProtoReflect.Descriptor instead.
func (*WatchSyncProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{0}
}

func (x *WatchSyncProviderDescriptor) GetAuthMethods() []WatchSyncAuthMethod {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

func (x *WatchSyncProviderDescriptor) GetExportWatched() bool {
	if x != nil {
		return x.ExportWatched
	}
	return false
}

func (x *WatchSyncProviderDescriptor) GetExportUnwatched() bool {
	if x != nil {
		return x.ExportUnwatched
	}
	return false
}

func (x *WatchSyncProviderDescriptor) GetImportWatched() bool {
	if x != nil {
		return x.ImportWatched
	}
	return false
}

func (x *WatchSyncProviderDescriptor) GetImportProgress() bool {
	if x != nil {
		return x.ImportProgress
	}
	return false
}

func (x *WatchSyncProviderDescriptor) GetSupportedMediaTypes() []string {
	if x != nil {
		return x.SupportedMediaTypes
	}
	return nil
}

func (x *WatchSyncProviderDescriptor) GetExternalIdNamespaces() []string {
	if x != nil {
		return x.ExternalIdNamespaces
	}
	return nil
}

func (x *WatchSyncProviderDescriptor) GetMaxBatchSize() int32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

type WatchSyncProviderConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Values map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The host encrypts these values at rest and includes them only in RPCs that
	// need them. They are never Runtime.Configure entries.
	SecretValues  map[string]string `protobuf:"bytes,2,rep,name=secret_values,json=secretValues,proto3" json:"secret_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncProviderConfig) Reset() {
	*x = WatchSyncProviderConfig{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncProviderConfig) ProtoMessage() {}

func (x *WatchSyncProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncProviderConfig.ProtoReflect.Descriptor instead.
func (*WatchSyncProviderConfig) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{1}
}

func (x *WatchSyncProviderConfig) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *WatchSyncProviderConfig) GetSecretValues() map[string]string {
	if x != nil {
		return x.SecretValues
	}
	return nil
}

type WatchSyncCredentials struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AccessToken  string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TokenType    string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scopes       []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Provider-specific token fields. The host encrypts the credential as one
	// opaque record and does not interpret these values.
	SecretAttributes map[string]string `protobuf:"bytes,6,rep,name=secret_attributes,json=secretAttributes,proto3" json:"secret_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WatchSyncCredentials) Reset() {
	*x = WatchSyncCredentials{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncCredentials) ProtoMessage() {}

func (x *WatchSyncCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncCredentials.ProtoReflect.Descriptor instead.
func (*WatchSyncCredentials) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{2}
}

func (x *WatchSyncCredentials) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *WatchSyncCredentials) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *WatchSyncCredentials) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *WatchSyncCredentials) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *WatchSyncCredentials) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *WatchSyncCredentials) GetSecretAttributes() map[string]string {
	if x != nil {
		return x.SecretAttributes
	}
	return nil
}

type WatchSyncAccount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalSubject string                 `protobuf:"bytes,1,opt,name=external_subject,json=externalSubject,proto3" json:"external_subject,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ProfileUrl      string                 `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchSyncAccount) Reset() {
	*x = WatchSyncAccount{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncAccount) ProtoMessage() {}

func (x *WatchSyncAccount) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncAccount.ProtoReflect.Descriptor instead.
func (*WatchSyncAccount) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{3}
}

func (x *WatchSyncAccount) GetExternalSubject() string {
	if x != nil {
		return x.ExternalSubject
	}
	return ""
}

func (x *WatchSyncAccount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WatchSyncAccount) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *WatchSyncAccount) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *WatchSyncAccount) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

type WatchSyncFault struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  WatchSyncFaultCode     `protobuf:"varint,1,opt,name=code,proto3,enum=silo.plugin.v1.WatchSyncFaultCode" json:"code,omitempty"`
	// Safe for persistence and operator display. Must not contain credentials,
	// authorization codes, provider response bodies, or other secrets.
	SafeMessage   string               `protobuf:"bytes,2,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	RetryAfter    *durationpb.Duration `protobuf:"bytes,3,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncFault) Reset() {
	*x = WatchSyncFault{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncFault) ProtoMessage() {}

func (x *WatchSyncFault) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncFault.ProtoReflect.Descriptor instead.
func (*WatchSyncFault) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{4}
}

func (x *WatchSyncFault) GetCode() WatchSyncFaultCode {
	if x != nil {
		return x.Code
	}
	return WatchSyncFaultCode_WATCH_SYNC_FAULT_CODE_UNSPECIFIED
}

func (x *WatchSyncFault) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

func (x *WatchSyncFault) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

type WatchSyncInitAuthorizeRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId   string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	RedirectUri    string                   `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	// Generated, stored, and validated by the host.
	State         string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncInitAuthorizeRequest) Reset() {
	*x = WatchSyncInitAuthorizeRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncInitAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncInitAuthorizeRequest) ProtoMessage() {}

func (x *WatchSyncInitAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncInitAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncInitAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{5}
}

func (x *WatchSyncInitAuthorizeRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncInitAuthorizeRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncInitAuthorizeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *WatchSyncInitAuthorizeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type WatchSyncInitAuthorizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	// Plugin-defined flow data. The host encrypts it until callback completion
	// and never returns it through the public HTTP API.
	ProviderState []byte          `protobuf:"bytes,2,opt,name=provider_state,json=providerState,proto3" json:"provider_state,omitempty"`
	Fault         *WatchSyncFault `protobuf:"bytes,3,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncInitAuthorizeResponse) Reset() {
	*x = WatchSyncInitAuthorizeResponse{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncInitAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncInitAuthorizeResponse) ProtoMessage() {}

func (x *WatchSyncInitAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncInitAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*WatchSyncInitAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{6}
}

func (x *WatchSyncInitAuthorizeResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *WatchSyncInitAuthorizeResponse) GetProviderState() []byte {
	if x != nil {
		return x.ProviderState
	}
	return nil
}

func (x *WatchSyncInitAuthorizeResponse) GetFault() *WatchSyncFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type WatchSyncExchangeCodeRequest struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId      string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig    *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	RedirectUri       string                   `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	AuthorizationCode string                   `protobuf:"bytes,4,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	ProviderState     []byte                   `protobuf:"bytes,5,opt,name=provider_state,json=providerState,proto3" json:"provider_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchSyncExchangeCodeRequest) Reset() {
	*x = WatchSyncExchangeCodeRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncExchangeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncExchangeCodeRequest) ProtoMessage() {}

func (x *WatchSyncExchangeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncExchangeCodeRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncExchangeCodeRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{7}
}

func (x *WatchSyncExchangeCodeRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncExchangeCodeRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncExchangeCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *WatchSyncExchangeCodeRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *WatchSyncExchangeCodeRequest) GetProviderState() []byte {
	if x != nil {
		return x.ProviderState
	}
	return nil
}

type WatchSyncExchangeAPIKeyRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId   string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	// API key or manually-issued bearer token. The host does not persist this
	// request field unless the plugin validates and returns it as credentials.
	ApiKey        string `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncExchangeAPIKeyRequest) Reset() {
	*x = WatchSyncExchangeAPIKeyRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncExchangeAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncExchangeAPIKeyRequest) ProtoMessage() {}

func (x *WatchSyncExchangeAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncExchangeAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncExchangeAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{8}
}

func (x *WatchSyncExchangeAPIKeyRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncExchangeAPIKeyRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncExchangeAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type WatchSyncRefreshCredentialsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId   string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	Credentials    *WatchSyncCredentials    `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchSyncRefreshCredentialsRequest) Reset() {
	*x = WatchSyncRefreshCredentialsRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncRefreshCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncRefreshCredentialsRequest) ProtoMessage() {}

func (x *WatchSyncRefreshCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncRefreshCredentialsRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncRefreshCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{9}
}

func (x *WatchSyncRefreshCredentialsRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncRefreshCredentialsRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncRefreshCredentialsRequest) GetCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type WatchSyncCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *WatchSyncCredentials  `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Account       *WatchSyncAccount      `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Fault         *WatchSyncFault        `protobuf:"bytes,3,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncCredentialResponse) Reset() {
	*x = WatchSyncCredentialResponse{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncCredentialResponse) ProtoMessage() {}

func (x *WatchSyncCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncCredentialResponse.ProtoReflect.Descriptor instead.
func (*WatchSyncCredentialResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{10}
}

func (x *WatchSyncCredentialResponse) GetCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *WatchSyncCredentialResponse) GetAccount() *WatchSyncAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *WatchSyncCredentialResponse) GetFault() *WatchSyncFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type WatchSyncGetAccountRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId   string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	Credentials    *WatchSyncCredentials    `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchSyncGetAccountRequest) Reset() {
	*x = WatchSyncGetAccountRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncGetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncGetAccountRequest) ProtoMessage() {}

func (x *WatchSyncGetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncGetAccountRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncGetAccountRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{11}
}

func (x *WatchSyncGetAccountRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncGetAccountRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncGetAccountRequest) GetCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type WatchSyncGetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *WatchSyncAccount      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Fault         *WatchSyncFault        `protobuf:"bytes,2,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncGetAccountResponse) Reset() {
	*x = WatchSyncGetAccountResponse{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncGetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncGetAccountResponse) ProtoMessage() {}

func (x *WatchSyncGetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncGetAccountResponse.ProtoReflect.Descriptor instead.
func (*WatchSyncGetAccountResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{12}
}

func (x *WatchSyncGetAccountResponse) GetAccount() *WatchSyncAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *WatchSyncGetAccountResponse) GetFault() *WatchSyncFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type WatchSyncMedia struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MediaItemId           string                 `protobuf:"bytes,1,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	MediaType             string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Title                 string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle         string                 `protobuf:"bytes,4,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Year                  int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	ExternalIds           map[string]string      `protobuf:"bytes,6,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeriesMediaItemId     string                 `protobuf:"bytes,7,opt,name=series_media_item_id,json=seriesMediaItemId,proto3" json:"series_media_item_id,omitempty"`
	SeriesTitle           string                 `protobuf:"bytes,8,opt,name=series_title,json=seriesTitle,proto3" json:"series_title,omitempty"`
	SeriesYear            int32                  `protobuf:"varint,9,opt,name=series_year,json=seriesYear,proto3" json:"series_year,omitempty"`
	SeriesExternalIds     map[string]string      `protobuf:"bytes,10,rep,name=series_external_ids,json=seriesExternalIds,proto3" json:"series_external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeasonNumber          int32                  `protobuf:"varint,11,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber         int32                  `protobuf:"varint,12,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	AbsoluteEpisodeNumber int32                  `protobuf:"varint,13,opt,name=absolute_episode_number,json=absoluteEpisodeNumber,proto3" json:"absolute_episode_number,omitempty"`
	SeriesEpisodeCount    int32                  `protobuf:"varint,14,opt,name=series_episode_count,json=seriesEpisodeCount,proto3" json:"series_episode_count,omitempty"`
	Metadata              *structpb.Struct       `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WatchSyncMedia) Reset() {
	*x = WatchSyncMedia{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncMedia) ProtoMessage() {}

func (x *WatchSyncMedia) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncMedia.ProtoReflect.Descriptor instead.
func (*WatchSyncMedia) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{13}
}

func (x *WatchSyncMedia) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *WatchSyncMedia) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *WatchSyncMedia) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WatchSyncMedia) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *WatchSyncMedia) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *WatchSyncMedia) GetExternalIds() map[string]string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *WatchSyncMedia) GetSeriesMediaItemId() string {
	if x != nil {
		return x.SeriesMediaItemId
	}
	return ""
}

func (x *WatchSyncMedia) GetSeriesTitle() string {
	if x != nil {
		return x.SeriesTitle
	}
	return ""
}

func (x *WatchSyncMedia) GetSeriesYear() int32 {
	if x != nil {
		return x.SeriesYear
	}
	return 0
}

func (x *WatchSyncMedia) GetSeriesExternalIds() map[string]string {
	if x != nil {
		return x.SeriesExternalIds
	}
	return nil
}

func (x *WatchSyncMedia) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *WatchSyncMedia) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *WatchSyncMedia) GetAbsoluteEpisodeNumber() int32 {
	if x != nil {
		return x.AbsoluteEpisodeNumber
	}
	return 0
}

func (x *WatchSyncMedia) GetSeriesEpisodeCount() int32 {
	if x != nil {
		return x.SeriesEpisodeCount
	}
	return 0
}

func (x *WatchSyncMedia) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WatchSyncEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable across retries and unique within one provider connection.
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Operation         WatchSyncOperation     `protobuf:"varint,2,opt,name=operation,proto3,enum=silo.plugin.v1.WatchSyncOperation" json:"operation,omitempty"`
	Origin            WatchSyncOrigin        `protobuf:"varint,3,opt,name=origin,proto3,enum=silo.plugin.v1.WatchSyncOrigin" json:"origin,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Media             *WatchSyncMedia        `protobuf:"bytes,5,opt,name=media,proto3" json:"media,omitempty"`
	WatchHistoryId    string                 `protobuf:"bytes,6,opt,name=watch_history_id,json=watchHistoryId,proto3" json:"watch_history_id,omitempty"`
	PlaybackSessionId string                 `protobuf:"bytes,7,opt,name=playback_session_id,json=playbackSessionId,proto3" json:"playback_session_id,omitempty"`
	PositionSeconds   float64                `protobuf:"fixed64,8,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	DurationSeconds   float64                `protobuf:"fixed64,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CompletionPercent float64                `protobuf:"fixed64,10,opt,name=completion_percent,json=completionPercent,proto3" json:"completion_percent,omitempty"`
	PlayCount         int32                  `protobuf:"varint,11,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchSyncEvent) Reset() {
	*x = WatchSyncEvent{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncEvent) ProtoMessage() {}

func (x *WatchSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncEvent.ProtoReflect.Descriptor instead.
func (*WatchSyncEvent) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{14}
}

func (x *WatchSyncEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WatchSyncEvent) GetOperation() WatchSyncOperation {
	if x != nil {
		return x.Operation
	}
	return WatchSyncOperation_WATCH_SYNC_OPERATION_UNSPECIFIED
}

func (x *WatchSyncEvent) GetOrigin() WatchSyncOrigin {
	if x != nil {
		return x.Origin
	}
	return WatchSyncOrigin_WATCH_SYNC_ORIGIN_UNSPECIFIED
}

func (x *WatchSyncEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *WatchSyncEvent) GetMedia() *WatchSyncMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *WatchSyncEvent) GetWatchHistoryId() string {
	if x != nil {
		return x.WatchHistoryId
	}
	return ""
}

func (x *WatchSyncEvent) GetPlaybackSessionId() string {
	if x != nil {
		return x.PlaybackSessionId
	}
	return ""
}

func (x *WatchSyncEvent) GetPositionSeconds() float64 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *WatchSyncEvent) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *WatchSyncEvent) GetCompletionPercent() float64 {
	if x != nil {
		return x.CompletionPercent
	}
	return 0
}

func (x *WatchSyncEvent) GetPlayCount() int32 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

type WatchSyncApplyEventsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId   string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	Credentials    *WatchSyncCredentials    `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// Ordered desired-state events. Duplicate event IDs must not be interpreted
	// as increments; ApplyEvents is an at-least-once delivery contract.
	Events        []*WatchSyncEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncApplyEventsRequest) Reset() {
	*x = WatchSyncApplyEventsRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncApplyEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncApplyEventsRequest) ProtoMessage() {}

func (x *WatchSyncApplyEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncApplyEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncApplyEventsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{15}
}

func (x *WatchSyncApplyEventsRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncApplyEventsRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncApplyEventsRequest) GetCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *WatchSyncApplyEventsRequest) GetEvents() []*WatchSyncEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type WatchSyncApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        WatchSyncApplyStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=silo.plugin.v1.WatchSyncApplyStatus" json:"status,omitempty"`
	SafeMessage   string                 `protobuf:"bytes,3,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	RetryAfter    *durationpb.Duration   `protobuf:"bytes,4,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSyncApplyResult) Reset() {
	*x = WatchSyncApplyResult{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncApplyResult) ProtoMessage() {}

func (x *WatchSyncApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncApplyResult.ProtoReflect.Descriptor instead.
func (*WatchSyncApplyResult) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{16}
}

func (x *WatchSyncApplyResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WatchSyncApplyResult) GetStatus() WatchSyncApplyStatus {
	if x != nil {
		return x.Status
	}
	return WatchSyncApplyStatus_WATCH_SYNC_APPLY_STATUS_UNSPECIFIED
}

func (x *WatchSyncApplyResult) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

func (x *WatchSyncApplyResult) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

type WatchSyncApplyEventsResponse struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Results            []*WatchSyncApplyResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	UpdatedCredentials *WatchSyncCredentials   `protobuf:"bytes,2,opt,name=updated_credentials,json=updatedCredentials,proto3" json:"updated_credentials,omitempty"`
	Fault              *WatchSyncFault         `protobuf:"bytes,3,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchSyncApplyEventsResponse) Reset() {
	*x = WatchSyncApplyEventsResponse{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncApplyEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncApplyEventsResponse) ProtoMessage() {}

func (x *WatchSyncApplyEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncApplyEventsResponse.ProtoReflect.Descriptor instead.
func (*WatchSyncApplyEventsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{17}
}

func (x *WatchSyncApplyEventsResponse) GetResults() []*WatchSyncApplyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *WatchSyncApplyEventsResponse) GetUpdatedCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.UpdatedCredentials
	}
	return nil
}

func (x *WatchSyncApplyEventsResponse) GetFault() *WatchSyncFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type WatchSyncListRemoteStateRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	CapabilityId   string                   `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	ProviderConfig *WatchSyncProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	Credentials    *WatchSyncCredentials    `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Cursor         string                   `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageToken      string                   `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize       int32                    `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchSyncListRemoteStateRequest) Reset() {
	*x = WatchSyncListRemoteStateRequest{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncListRemoteStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncListRemoteStateRequest) ProtoMessage() {}

func (x *WatchSyncListRemoteStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncListRemoteStateRequest.ProtoReflect.Descriptor instead.
func (*WatchSyncListRemoteStateRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{18}
}

func (x *WatchSyncListRemoteStateRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *WatchSyncListRemoteStateRequest) GetProviderConfig() *WatchSyncProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

func (x *WatchSyncListRemoteStateRequest) GetCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *WatchSyncListRemoteStateRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *WatchSyncListRemoteStateRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *WatchSyncListRemoteStateRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type WatchSyncRemoteState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProviderItemKey string                 `protobuf:"bytes,1,opt,name=provider_item_key,json=providerItemKey,proto3" json:"provider_item_key,omitempty"`
	Media           *WatchSyncMedia        `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Progress        int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchSyncRemoteState) Reset() {
	*x = WatchSyncRemoteState{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncRemoteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncRemoteState) ProtoMessage() {}

func (x *WatchSyncRemoteState) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncRemoteState.ProtoReflect.Descriptor instead.
func (*WatchSyncRemoteState) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{19}
}

func (x *WatchSyncRemoteState) GetProviderItemKey() string {
	if x != nil {
		return x.ProviderItemKey
	}
	return ""
}

func (x *WatchSyncRemoteState) GetMedia() *WatchSyncMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *WatchSyncRemoteState) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *WatchSyncRemoteState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WatchSyncRemoteState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WatchSyncListRemoteStateResponse struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Items              []*WatchSyncRemoteState `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken      string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	NextCursor         string                  `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	CompleteSnapshot   bool                    `protobuf:"varint,4,opt,name=complete_snapshot,json=completeSnapshot,proto3" json:"complete_snapshot,omitempty"`
	UpdatedCredentials *WatchSyncCredentials   `protobuf:"bytes,5,opt,name=updated_credentials,json=updatedCredentials,proto3" json:"updated_credentials,omitempty"`
	Fault              *WatchSyncFault         `protobuf:"bytes,6,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchSyncListRemoteStateResponse) Reset() {
	*x = WatchSyncListRemoteStateResponse{}
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSyncListRemoteStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSyncListRemoteStateResponse) ProtoMessage() {}

func (x *WatchSyncListRemoteStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_watch_sync_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSyncListRemoteStateResponse.ProtoReflect.Descriptor instead.
func (*WatchSyncListRemoteStateResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP(), []int{20}
}

func (x *WatchSyncListRemoteStateResponse) GetItems() []*WatchSyncRemoteState {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *WatchSyncListRemoteStateResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *WatchSyncListRemoteStateResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *WatchSyncListRemoteStateResponse) GetCompleteSnapshot() bool {
	if x != nil {
		return x.CompleteSnapshot
	}
	return false
}

func (x *WatchSyncListRemoteStateResponse) GetUpdatedCredentials() *WatchSyncCredentials {
	if x != nil {
		return x.UpdatedCredentials
	}
	return nil
}

func (x *WatchSyncListRemoteStateResponse) GetFault() *WatchSyncFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

var File_silo_plugin_v1_watch_sync_provider_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_watch_sync_provider_proto_rawDesc = "" +
	"\n" +
	"(silo/plugin/v1/watch_sync_provider.proto\x12\x0esilo.plugin.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x03\n" +
	"\x1bWatchSyncProviderDescriptor\x12F\n" +
	"\fauth_methods\x18\x01 \x03(\x0e2#.silo.plugin.v1.WatchSyncAuthMethodR\vauthMethods\x12%\n" +
	"\x0eexport_watched\x18\x02 \x01(\bR\rexportWatched\x12)\n" +
	"\x10export_unwatched\x18\x03 \x01(\bR\x0fexportUnwatched\x12%\n" +
	"\x0eimport_watched\x18\x04 \x01(\bR\rimportWatched\x12'\n" +
	"\x0fimport_progress\x18\x05 \x01(\bR\x0eimportProgress\x122\n" +
	"\x15supported_media_types\x18\x06 \x03(\tR\x13supportedMediaTypes\x124\n" +
	"\x16external_id_namespaces\x18\a \x03(\tR\x14externalIdNamespaces\x12$\n" +
	"\x0emax_batch_size\x18\b \x01(\x05R\fmaxBatchSize\"\xc2\x02\n" +
	"\x17WatchSyncProviderConfig\x12K\n" +
	"\x06values\x18\x01 \x03(\v23.silo.plugin.v1.WatchSyncProviderConfig.ValuesEntryR\x06values\x12^\n" +
	"\rsecret_values\x18\x02 \x03(\v29.silo.plugin.v1.WatchSyncProviderConfig.SecretValuesEntryR\fsecretValues\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11SecretValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x02\n" +
	"\x14WatchSyncCredentials\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12g\n" +
	"\x11secret_attributes\x18\x06 \x03(\v2:.silo.plugin.v1.WatchSyncCredentials.SecretAttributesEntryR\x10secretAttributes\x1aC\n" +
	"\x15SecretAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x10WatchSyncAccount\x12)\n" +
	"\x10external_subject\x18\x01 \x01(\tR\x0fexternalSubject\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1f\n" +
	"\vprofile_url\x18\x05 \x01(\tR\n" +
	"profileUrl\"\xa7\x01\n" +
	"\x0eWatchSyncFault\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".silo.plugin.v1.WatchSyncFaultCodeR\x04code\x12!\n" +
	"\fsafe_message\x18\x02 \x01(\tR\vsafeMessage\x12:\n" +
	"\vretry_after\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\"\xcf\x01\n" +
	"\x1dWatchSyncInitAuthorizeRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\xaa\x01\n" +
	"\x1eWatchSyncInitAuthorizeResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12%\n" +
	"\x0eprovider_state\x18\x02 \x01(\fR\rproviderState\x124\n" +
	"\x05fault\x18\x03 \x01(\v2\x1e.silo.plugin.v1.WatchSyncFaultR\x05fault\"\x8e\x02\n" +
	"\x1cWatchSyncExchangeCodeRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12-\n" +
	"\x12authorization_code\x18\x04 \x01(\tR\x11authorizationCode\x12%\n" +
	"\x0eprovider_state\x18\x05 \x01(\fR\rproviderState\"\xb0\x01\n" +
	"\x1eWatchSyncExchangeAPIKeyRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"\xe3\x01\n" +
	"\"WatchSyncRefreshCredentialsRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12F\n" +
	"\vcredentials\x18\x03 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\vcredentials\"\xd7\x01\n" +
	"\x1bWatchSyncCredentialResponse\x12F\n" +
	"\vcredentials\x18\x01 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\vcredentials\x12:\n" +
	"\aaccount\x18\x02 \x01(\v2 .silo.plugin.v1.WatchSyncAccountR\aaccount\x124\n" +
	"\x05fault\x18\x03 \x01(\v2\x1e.silo.plugin.v1.WatchSyncFaultR\x05fault\"\xdb\x01\n" +
	"\x1aWatchSyncGetAccountRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12F\n" +
	"\vcredentials\x18\x03 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\vcredentials\"\x8f\x01\n" +
	"\x1bWatchSyncGetAccountResponse\x12:\n" +
	"\aaccount\x18\x01 \x01(\v2 .silo.plugin.v1.WatchSyncAccountR\aaccount\x124\n" +
	"\x05fault\x18\x02 \x01(\v2\x1e.silo.plugin.v1.WatchSyncFaultR\x05fault\"\xc5\x06\n" +
	"\x0eWatchSyncMedia\x12\"\n" +
	"\rmedia_item_id\x18\x01 \x01(\tR\vmediaItemId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x04 \x01(\tR\roriginalTitle\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12R\n" +
	"\fexternal_ids\x18\x06 \x03(\v2/.silo.plugin.v1.WatchSyncMedia.ExternalIdsEntryR\vexternalIds\x12/\n" +
	"\x14series_media_item_id\x18\a \x01(\tR\x11seriesMediaItemId\x12!\n" +
	"\fseries_title\x18\b \x01(\tR\vseriesTitle\x12\x1f\n" +
	"\vseries_year\x18\t \x01(\x05R\n" +
	"seriesYear\x12e\n" +
	"\x13series_external_ids\x18\n" +
	" \x03(\v25.silo.plugin.v1.WatchSyncMedia.SeriesExternalIdsEntryR\x11seriesExternalIds\x12#\n" +
	"\rseason_number\x18\v \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\f \x01(\x05R\repisodeNumber\x126\n" +
	"\x17absolute_episode_number\x18\r \x01(\x05R\x15absoluteEpisodeNumber\x120\n" +
	"\x14series_episode_count\x18\x0e \x01(\x05R\x12seriesEpisodeCount\x123\n" +
	"\bmetadata\x18\x0f \x01(\v2\x17.google.protobuf.StructR\bmetadata\x1a>\n" +
	"\x10ExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16SeriesExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x04\n" +
	"\x0eWatchSyncEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12@\n" +
	"\toperation\x18\x02 \x01(\x0e2\".silo.plugin.v1.WatchSyncOperationR\toperation\x127\n" +
	"\x06origin\x18\x03 \x01(\x0e2\x1f.silo.plugin.v1.WatchSyncOriginR\x06origin\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x124\n" +
	"\x05media\x18\x05 \x01(\v2\x1e.silo.plugin.v1.WatchSyncMediaR\x05media\x12(\n" +
	"\x10watch_history_id\x18\x06 \x01(\tR\x0ewatchHistoryId\x12.\n" +
	"\x13playback_session_id\x18\a \x01(\tR\x11playbackSessionId\x12)\n" +
	"\x10position_seconds\x18\b \x01(\x01R\x0fpositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x01R\x0fdurationSeconds\x12-\n" +
	"\x12completion_percent\x18\n" +
	" \x01(\x01R\x11completionPercent\x12\x1d\n" +
	"\n" +
	"play_count\x18\v \x01(\x05R\tplayCount\"\x94\x02\n" +
	"\x1bWatchSyncApplyEventsRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12F\n" +
	"\vcredentials\x18\x03 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\vcredentials\x126\n" +
	"\x06events\x18\x04 \x03(\v2\x1e.silo.plugin.v1.WatchSyncEventR\x06events\"\xce\x01\n" +
	"\x14WatchSyncApplyResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.silo.plugin.v1.WatchSyncApplyStatusR\x06status\x12!\n" +
	"\fsafe_message\x18\x03 \x01(\tR\vsafeMessage\x12:\n" +
	"\vretry_after\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\"\xeb\x01\n" +
	"\x1cWatchSyncApplyEventsResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.silo.plugin.v1.WatchSyncApplyResultR\aresults\x12U\n" +
	"\x13updated_credentials\x18\x02 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\x12updatedCredentials\x124\n" +
	"\x05fault\x18\x03 \x01(\v2\x1e.silo.plugin.v1.WatchSyncFaultR\x05fault\"\xb4\x02\n" +
	"\x1fWatchSyncListRemoteStateRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12P\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2'.silo.plugin.v1.WatchSyncProviderConfigR\x0eproviderConfig\x12F\n" +
	"\vcredentials\x18\x03 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\vcredentials\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xe7\x01\n" +
	"\x14WatchSyncRemoteState\x12*\n" +
	"\x11provider_item_key\x18\x01 \x01(\tR\x0fproviderItemKey\x124\n" +
	"\x05media\x18\x02 \x01(\v2\x1e.silo.plugin.v1.WatchSyncMediaR\x05media\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe1\x02\n" +
	" WatchSyncListRemoteStateResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.silo.plugin.v1.WatchSyncRemoteStateR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\x12+\n" +
	"\x11complete_snapshot\x18\x04 \x01(\bR\x10completeSnapshot\x12U\n" +
	"\x13updated_credentials\x18\x05 \x01(\v2$.silo.plugin.v1.WatchSyncCredentialsR\x12updatedCredentials\x124\n" +
	"\x05fault\x18\x06 \x01(\v2\x1e.silo.plugin.v1.WatchSyncFaultR\x05fault*\x90\x01\n" +
	"\x13WatchSyncAuthMethod\x12&\n" +
	"\"WATCH_SYNC_AUTH_METHOD_UNSPECIFIED\x10\x00\x12-\n" +
	")WATCH_SYNC_AUTH_METHOD_AUTHORIZATION_CODE\x10\x01\x12\"\n" +
	"\x1eWATCH_SYNC_AUTH_METHOD_API_KEY\x10\x02*\x8a\x01\n" +
	"\x12WatchSyncOperation\x12$\n" +
	" WATCH_SYNC_OPERATION_UNSPECIFIED\x10\x00\x12%\n" +
	"!WATCH_SYNC_OPERATION_MARK_WATCHED\x10\x01\x12'\n" +
	"#WATCH_SYNC_OPERATION_MARK_UNWATCHED\x10\x02*\xa3\x01\n" +
	"\x0fWatchSyncOrigin\x12!\n" +
	"\x1dWATCH_SYNC_ORIGIN_UNSPECIFIED\x10\x00\x12)\n" +
	"%WATCH_SYNC_ORIGIN_PLAYBACK_COMPLETION\x10\x01\x12\x1c\n" +
	"\x18WATCH_SYNC_ORIGIN_MANUAL\x10\x02\x12$\n" +
	" WATCH_SYNC_ORIGIN_RECONCILIATION\x10\x03*\xd4\x01\n" +
	"\x14WatchSyncApplyStatus\x12'\n" +
	"#WATCH_SYNC_APPLY_STATUS_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fWATCH_SYNC_APPLY_STATUS_APPLIED\x10\x01\x12%\n" +
	"!WATCH_SYNC_APPLY_STATUS_NO_CHANGE\x10\x02\x12!\n" +
	"\x1dWATCH_SYNC_APPLY_STATUS_RETRY\x10\x03\x12$\n" +
	" WATCH_SYNC_APPLY_STATUS_REJECTED\x10\x04*\xb3\x02\n" +
	"\x12WatchSyncFaultCode\x12%\n" +
	"!WATCH_SYNC_FAULT_CODE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fWATCH_SYNC_FAULT_CODE_TEMPORARY\x10\x01\x12&\n" +
	"\"WATCH_SYNC_FAULT_CODE_RATE_LIMITED\x10\x02\x12,\n" +
	"(WATCH_SYNC_FAULT_CODE_INVALID_CREDENTIAL\x10\x03\x12+\n" +
	"'WATCH_SYNC_FAULT_CODE_PERMISSION_DENIED\x10\x04\x12)\n" +
	"%WATCH_SYNC_FAULT_CODE_INVALID_REQUEST\x10\x05\x12#\n" +
	"\x1fWATCH_SYNC_FAULT_CODE_PERMANENT\x10\x062\x9b\x06\n" +
	"\x11WatchSyncProvider\x12n\n" +
	"\rInitAuthorize\x12-.silo.plugin.v1.WatchSyncInitAuthorizeRequest\x1a..silo.plugin.v1.WatchSyncInitAuthorizeResponse\x12i\n" +
	"\fExchangeCode\x12,.silo.plugin.v1.WatchSyncExchangeCodeRequest\x1a+.silo.plugin.v1.WatchSyncCredentialResponse\x12m\n" +
	"\x0eExchangeAPIKey\x12..silo.plugin.v1.WatchSyncExchangeAPIKeyRequest\x1a+.silo.plugin.v1.WatchSyncCredentialResponse\x12u\n" +
	"\x12RefreshCredentials\x122.silo.plugin.v1.WatchSyncRefreshCredentialsRequest\x1a+.silo.plugin.v1.WatchSyncCredentialResponse\x12e\n" +
	"\n" +
	"GetAccount\x12*.silo.plugin.v1.WatchSyncGetAccountRequest\x1a+.silo.plugin.v1.WatchSyncGetAccountResponse\x12h\n" +
	"\vApplyEvents\x12+.silo.plugin.v1.WatchSyncApplyEventsRequest\x1a,.silo.plugin.v1.WatchSyncApplyEventsResponse\x12t\n" +
	"\x0fListRemoteState\x12/.silo.plugin.v1.WatchSyncListRemoteStateRequest\x1a0.silo.plugin.v1.WatchSyncListRemoteStateResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_watch_sync_provider_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_watch_sync_provider_proto_rawDescData []byte
)

func file_silo_plugin_v1_watch_sync_provider_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_watch_sync_provider_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_watch_sync_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_watch_sync_provider_proto_rawDesc), len(file_silo_plugin_v1_watch_sync_provider_proto_rawDesc)))
	})
	return file_silo_plugin_v1_watch_sync_provider_proto_rawDescData
}

var file_silo_plugin_v1_watch_sync_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_silo_plugin_v1_watch_sync_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_silo_plugin_v1_watch_sync_provider_proto_goTypes = []any{
	(WatchSyncAuthMethod)(0),                   // 0: silo.plugin.v1.WatchSyncAuthMethod
	(WatchSyncOperation)(0),                    // 1: silo.plugin.v1.WatchSyncOperation
	(WatchSyncOrigin)(0),                       // 2: silo.plugin.v1.WatchSyncOrigin
	(WatchSyncApplyStatus)(0),                  // 3: silo.plugin.v1.WatchSyncApplyStatus
	(WatchSyncFaultCode)(0),                    // 4: silo.plugin.v1.WatchSyncFaultCode
	(*WatchSyncProviderDescriptor)(nil),        // 5: silo.plugin.v1.WatchSyncProviderDescriptor
	(*WatchSyncProviderConfig)(nil),            // 6: silo.plugin.v1.WatchSyncProviderConfig
	(*WatchSyncCredentials)(nil),               // 7: silo.plugin.v1.WatchSyncCredentials
	(*WatchSyncAccount)(nil),                   // 8: silo.plugin.v1.WatchSyncAccount
	(*WatchSyncFault)(nil),                     // 9: silo.plugin.v1.WatchSyncFault
	(*WatchSyncInitAuthorizeRequest)(nil),      // 10: silo.plugin.v1.WatchSyncInitAuthorizeRequest
	(*WatchSyncInitAuthorizeResponse)(nil),     // 11: silo.plugin.v1.WatchSyncInitAuthorizeResponse
	(*WatchSyncExchangeCodeRequest)(nil),       // 12: silo.plugin.v1.WatchSyncExchangeCodeRequest
	(*WatchSyncExchangeAPIKeyRequest)(nil),     // 13: silo.plugin.v1.WatchSyncExchangeAPIKeyRequest
	(*WatchSyncRefreshCredentialsRequest)(nil), // 14: silo.plugin.v1.WatchSyncRefreshCredentialsRequest
	(*WatchSyncCredentialResponse)(nil),        // 15: silo.plugin.v1.WatchSyncCredentialResponse
	(*WatchSyncGetAccountRequest)(nil),         // 16: silo.plugin.v1.WatchSyncGetAccountRequest
	(*WatchSyncGetAccountResponse)(nil),        // 17: silo.plugin.v1.WatchSyncGetAccountResponse
	(*WatchSyncMedia)(nil),                     // 18: silo.plugin.v1.WatchSyncMedia
	(*WatchSyncEvent)(nil),                     // 19: silo.plugin.v1.WatchSyncEvent
	(*WatchSyncApplyEventsRequest)(nil),        // 20: silo.plugin.v1.WatchSyncApplyEventsRequest
	(*WatchSyncApplyResult)(nil),               // 21: silo.plugin.v1.WatchSyncApplyResult
	(*WatchSyncApplyEventsResponse)(nil),       // 22: silo.plugin.v1.WatchSyncApplyEventsResponse
	(*WatchSyncListRemoteStateRequest)(nil),    // 23: silo.plugin.v1.WatchSyncListRemoteStateRequest
	(*WatchSyncRemoteState)(nil),               // 24: silo.plugin.v1.WatchSyncRemoteState
	(*WatchSyncListRemoteStateResponse)(nil),   // 25: silo.plugin.v1.WatchSyncListRemoteStateResponse
	nil,                                        // 26: silo.plugin.v1.WatchSyncProviderConfig.ValuesEntry
	nil,                                        // 27: silo.plugin.v1.WatchSyncProviderConfig.SecretValuesEntry
	nil,                                        // 28: silo.plugin.v1.WatchSyncCredentials.SecretAttributesEntry
	nil,                                        // 29: silo.plugin.v1.WatchSyncMedia.ExternalIdsEntry
	nil,                                        // 30: silo.plugin.v1.WatchSyncMedia.SeriesExternalIdsEntry
	(*timestamppb.Timestamp)(nil),              // 31: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                // 32: google.protobuf.Duration
	(*structpb.Struct)(nil),                    // 33: google.protobuf.Struct
}
var file_silo_plugin_v1_watch_sync_provider_proto_depIdxs = []int32{
	0,  // 0: silo.plugin.v1.WatchSyncProviderDescriptor.auth_methods:type_name -> silo.plugin.v1.WatchSyncAuthMethod
	26, // 1: silo.plugin.v1.WatchSyncProviderConfig.values:type_name -> silo.plugin.v1.WatchSyncProviderConfig.ValuesEntry
	27, // 2: silo.plugin.v1.WatchSyncProviderConfig.secret_values:type_name -> silo.plugin.v1.WatchSyncProviderConfig.SecretValuesEntry
	31, // 3: silo.plugin.v1.WatchSyncCredentials.expires_at:type_name -> google.protobuf.Timestamp
	28, // 4: silo.plugin.v1.WatchSyncCredentials.secret_attributes:type_name -> silo.plugin.v1.WatchSyncCredentials.SecretAttributesEntry
	4,  // 5: silo.plugin.v1.WatchSyncFault.code:type_name -> silo.plugin.v1.WatchSyncFaultCode
	32, // 6: silo.plugin.v1.WatchSyncFault.retry_after:type_name -> google.protobuf.Duration
	6,  // 7: silo.plugin.v1.WatchSyncInitAuthorizeRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	9,  // 8: silo.plugin.v1.WatchSyncInitAuthorizeResponse.fault:type_name -> silo.plugin.v1.WatchSyncFault
	6,  // 9: silo.plugin.v1.WatchSyncExchangeCodeRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	6,  // 10: silo.plugin.v1.WatchSyncExchangeAPIKeyRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	6,  // 11: silo.plugin.v1.WatchSyncRefreshCredentialsRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	7,  // 12: silo.plugin.v1.WatchSyncRefreshCredentialsRequest.credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	7,  // 13: silo.plugin.v1.WatchSyncCredentialResponse.credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	8,  // 14: silo.plugin.v1.WatchSyncCredentialResponse.account:type_name -> silo.plugin.v1.WatchSyncAccount
	9,  // 15: silo.plugin.v1.WatchSyncCredentialResponse.fault:type_name -> silo.plugin.v1.WatchSyncFault
	6,  // 16: silo.plugin.v1.WatchSyncGetAccountRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	7,  // 17: silo.plugin.v1.WatchSyncGetAccountRequest.credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	8,  // 18: silo.plugin.v1.WatchSyncGetAccountResponse.account:type_name -> silo.plugin.v1.WatchSyncAccount
	9,  // 19: silo.plugin.v1.WatchSyncGetAccountResponse.fault:type_name -> silo.plugin.v1.WatchSyncFault
	29, // 20: silo.plugin.v1.WatchSyncMedia.external_ids:type_name -> silo.plugin.v1.WatchSyncMedia.ExternalIdsEntry
	30, // 21: silo.plugin.v1.WatchSyncMedia.series_external_ids:type_name -> silo.plugin.v1.WatchSyncMedia.SeriesExternalIdsEntry
	33, // 22: silo.plugin.v1.WatchSyncMedia.metadata:type_name -> google.protobuf.Struct
	1,  // 23: silo.plugin.v1.WatchSyncEvent.operation:type_name -> silo.plugin.v1.WatchSyncOperation
	2,  // 24: silo.plugin.v1.WatchSyncEvent.origin:type_name -> silo.plugin.v1.WatchSyncOrigin
	31, // 25: silo.plugin.v1.WatchSyncEvent.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 26: silo.plugin.v1.WatchSyncEvent.media:type_name -> silo.plugin.v1.WatchSyncMedia
	6,  // 27: silo.plugin.v1.WatchSyncApplyEventsRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	7,  // 28: silo.plugin.v1.WatchSyncApplyEventsRequest.credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	19, // 29: silo.plugin.v1.WatchSyncApplyEventsRequest.events:type_name -> silo.plugin.v1.WatchSyncEvent
	3,  // 30: silo.plugin.v1.WatchSyncApplyResult.status:type_name -> silo.plugin.v1.WatchSyncApplyStatus
	32, // 31: silo.plugin.v1.WatchSyncApplyResult.retry_after:type_name -> google.protobuf.Duration
	21, // 32: silo.plugin.v1.WatchSyncApplyEventsResponse.results:type_name -> silo.plugin.v1.WatchSyncApplyResult
	7,  // 33: silo.plugin.v1.WatchSyncApplyEventsResponse.updated_credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	9,  // 34: silo.plugin.v1.WatchSyncApplyEventsResponse.fault:type_name -> silo.plugin.v1.WatchSyncFault
	6,  // 35: silo.plugin.v1.WatchSyncListRemoteStateRequest.provider_config:type_name -> silo.plugin.v1.WatchSyncProviderConfig
	7,  // 36: silo.plugin.v1.WatchSyncListRemoteStateRequest.credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	18, // 37: silo.plugin.v1.WatchSyncRemoteState.media:type_name -> silo.plugin.v1.WatchSyncMedia
	31, // 38: silo.plugin.v1.WatchSyncRemoteState.updated_at:type_name -> google.protobuf.Timestamp
	24, // 39: silo.plugin.v1.WatchSyncListRemoteStateResponse.items:type_name -> silo.plugin.v1.WatchSyncRemoteState
	7,  // 40: silo.plugin.v1.WatchSyncListRemoteStateResponse.updated_credentials:type_name -> silo.plugin.v1.WatchSyncCredentials
	9,  // 41: silo.plugin.v1.WatchSyncListRemoteStateResponse.fault:type_name -> silo.plugin.v1.WatchSyncFault
	10, // 42: silo.plugin.v1.WatchSyncProvider.InitAuthorize:input_type -> silo.plugin.v1.WatchSyncInitAuthorizeRequest
	12, // 43: silo.plugin.v1.WatchSyncProvider.ExchangeCode:input_type -> silo.plugin.v1.WatchSyncExchangeCodeRequest
	13, // 44: silo.plugin.v1.WatchSyncProvider.ExchangeAPIKey:input_type -> silo.plugin.v1.WatchSyncExchangeAPIKeyRequest
	14, // 45: silo.plugin.v1.WatchSyncProvider.RefreshCredentials:input_type -> silo.plugin.v1.WatchSyncRefreshCredentialsRequest
	16, // 46: silo.plugin.v1.WatchSyncProvider.GetAccount:input_type -> silo.plugin.v1.WatchSyncGetAccountRequest
	20, // 47: silo.plugin.v1.WatchSyncProvider.ApplyEvents:input_type -> silo.plugin.v1.WatchSyncApplyEventsRequest
	23, // 48: silo.plugin.v1.WatchSyncProvider.ListRemoteState:input_type -> silo.plugin.v1.WatchSyncListRemoteStateRequest
	11, // 49: silo.plugin.v1.WatchSyncProvider.InitAuthorize:output_type -> silo.plugin.v1.WatchSyncInitAuthorizeResponse
	15, // 50: silo.plugin.v1.WatchSyncProvider.ExchangeCode:output_type -> silo.plugin.v1.WatchSyncCredentialResponse
	15, // 51: silo.plugin.v1.WatchSyncProvider.ExchangeAPIKey:output_type -> silo.plugin.v1.WatchSyncCredentialResponse
	15, // 52: silo.plugin.v1.WatchSyncProvider.RefreshCredentials:output_type -> silo.plugin.v1.WatchSyncCredentialResponse
	17, // 53: silo.plugin.v1.WatchSyncProvider.GetAccount:output_type -> silo.plugin.v1.WatchSyncGetAccountResponse
	22, // 54: silo.plugin.v1.WatchSyncProvider.ApplyEvents:output_type -> silo.plugin.v1.WatchSyncApplyEventsResponse
	25, // 55: silo.plugin.v1.WatchSyncProvider.ListRemoteState:output_type -> silo.plugin.v1.WatchSyncListRemoteStateResponse
	49, // [49:56] is the sub-list for method output_type
	42, // [42:49] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_watch_sync_provider_proto_init() }
func file_silo_plugin_v1_watch_sync_provider_proto_init() {
	if File_silo_plugin_v1_watch_sync_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_watch_sync_provider_proto_rawDesc), len(file_silo_plugin_v1_watch_sync_provider_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_watch_sync_provider_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_watch_sync_provider_proto_depIdxs,
		EnumInfos:         file_silo_plugin_v1_watch_sync_provider_proto_enumTypes,
		MessageInfos:      file_silo_plugin_v1_watch_sync_provider_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_watch_sync_provider_proto = out.File
	file_silo_plugin_v1_watch_sync_provider_proto_goTypes = nil
	file_silo_plugin_v1_watch_sync_provider_proto_depIdxs = nil
}
